# E {-}

economia na saúde

Uma disciplina científica que busca aplicar os princípios e regras da Econômia no campo do cuidado à saúde. Nota: a econômia na área da saúde inclui a avaliação do sistema de saúde e de políticas da saúde de um ponto de vista econômico, da demanda e do fornecimento de cuidados com a saúde, e de tecnologias e de intervenções médicas; também inclui o planejamento e a organização de recursos do sistema de saúde, a consideração e a avaliação de determinantes da saúde, e a análise da performance do sistema de saúde em termos da eficiência da equidade e da alocação.

health economics

A scientific discipline that seeks to apply the principles and rules of economics in the health care field. Note: Health economics includes evaluation of the health system and of health policies from an economic perspective, of the demand for and supply of health care, and of medical technologies and interventions; it also includes health system resources planning and organization, consideration and evaluation of the determinants of health, and analysis of health system performance in terms of equity and allocative efficiency.

******

efeito adverso

um efeito nocivo ou não intencionado de uma intervenção .

adverse effect

A noxious or unintended effect of an intervention.

******

efeito colateral

Veja efeito adverso e evento adverso. Nota: o termo efeito colateral, frequentemente utilizado como efeito adverso, é impreciso, pois um efeito pode ser secundário (um efeito colateral)de uma intervenção, sem ser nocivo.

side effect

See adverse effect and adverse event. Note: The term side effect, often used for adverse effect, is imprecise, in that an effect can be secondary (a side effect) to an intervention, without being noxious.

******

efeito do tratamento

O efeito no estado de saúde ou no bem estar dos indivíduos atribuído apenas a um tratamento ou intervenção. Nota: investigadores buscam estimar o verdadeiro efeito de um tratamento ou intervenção calculando a diferença entre o desfecho obtido no grupo experimental e no grupo controle. Conceito relacionado: tamanho do efeito.

treatment effect

The effect on the subjects’ health status or well-being attributable only to a treatment or intervention. Note: Investigators seek to estimate the true effect of a treatment or intervention by calculating the difference between the outcome obtained in the experimental group and the control group.
Related concept: effect size

******

efeito placebo

O efeito no estado de saúde do paciente (melhora ou piora) que pode ocorrer em função da expectativa do paciente com relação ao efeito que uma dada intervenção traria. Nota: o efeito placebo é independente do efeito sendo estudado (farmacológico, cirúrgico, etc.). Quando um placebo é dado ao grupo controle, ambos os grupos experimentarão esse efeito, tornando possível isolar o efeito específico da intervenção.

placebo effect

The effect on a patient’s health status (improvement or worsening) that may occur due to the patient’s expectation that a particular intervention will have an effect. Note: The placebo effect is independent of the effect being studied (pharmacological, surgical, etc.). When a placebo is given to the control group, both groups will experience this effect, making it possible to isolate the specific effect of the intervention.

******

efetividade

O benefício de se usar uma tecnologia, programa ou intervenção para endereçar um problema específico em condições gerais ou de rotina, ao invés de condições controladas, por exemplo, por um médico num hospital ou na casa de um paciente. Sinônimo: efetividade clínica.

effectiveness

The benefit of using a technology, programme or intervention to address a specific problem under general or routine conditions, rather than under controlled conditions, for example, by a physician in a hospital or by a patient at home. Syn.: clinical effectiveness.

******

efetividade clínica

veja efetividade

clinical effectiveness

See effectiveness.

******

eficácia  

O benefício de se usar uma tecnologia, programa ou intervenção para tratar um problema particular em condições ideais - por exemplo, no contexto da pesquisa em laboratório, ou num protocolo rigoroso para um ensaio clinico randomizado.

efficacy

The benefit of using a technology, programme or intervention to treat a particular problem under ideal conditions—for example, in the context of research in a laboratory or a rigourous protocol for a randomized clinical trial.

******

eficácia diagnóstica de um teste

O grau para o qual um teste, possuindo suas propriedades técnicas e acurácia, pode ser usado para se fazer um diagnóstico; a utilidade de um teste é também expressa em termos da sua influência na escolha do tratamento e na saúde de um indivíduo ou de uma população.

diagnostic test efficacy

The degree to which a test, owing to its technical properties and accuracy, can be used to make a diagnosis; the usefulness of a test is also expressed in terms of its influence on the choice of treatment and on the health of an individual or a population.

******

eficiência

A habilidade de obter o máximo benefício possível, à partir dos recursos disponíveis. Nota: é frequentemente definida como a razão entre o desfecho obtido e os recursos utilizados. (conceitos relacionados: eficiência alocativa e eficiência técnica).

efficiency

The ability to obtain the maximum possible benefit, given the resources available. Note: It is often the simple ratio between the outcome obtained and the resources used. (Related concepts: allocative efficiency and technical efficiency)

******

eficiência alocativa

A eficiência alocativa (um conceito econômico) refere-se à forma como as diferentes entradas de recursos são combinadas para produzir uma mistura de saídas diferentes.

allocative efficiency

The optimal distribution of healthcare resources required to produce a given level of health outcomes, taking into account consumer preferences.

Note 1: Related terms include efficiency and technical efficiency.

******

eficiência técnica

A habilidade em produzir a maioria ou os melhores efeitos com um nível especificado de recursos

technical efficiency

The ability to produce the most or the best effects with a specified level of resources.

******

EMBASE (Base de Dados da Excerpta Medica) 

Uma base de dados biomédica e farmacológica cobrindo 3.500 jornais de 110 países, publicados desce 1970. Nota: esta base de dados contém um grande número de publicações européias.

EMBASE (Excerpta Medica Database)

A biomedical and pharmacological database covering 3,500 journals from 110 countries published since 1970. Note: This database contains a large number of European publications.

******

empírico

Resultados baseados na experiência ou observação, ao invés de somente por raciocínio.

empirical

Results based on experience or observation, rather than on reasoning alone.

******

EMTREE (Árvore da Excerpta Medica)

Vocabulário controlado organizado em um dicionário para a base de dados EMBASE.

EMTREE (Excerpta Medica Tree)

Controlled vocabulary organized into a thesaurus for the EMBASE database.

******

ensaio aberto

Um ensaio clínico no qual o investigador e o indivíduo sabem quem está recebendo e qual é a intervenção. Nota: este termo é também isado quando apenas uma intervenção está sendo estudada, em estudos não cegados de longo termo de monitoração ou quando a cegagem é difícil ou não ética (comparção de um tratamento cirúrgico com um tratamento médico, por exemplo).

open-label trial

A clinical trial in which the investigator and the subject know who is receiving which intervention. Note: This term is also used when only one intervention is being studied, for unblinded long-term follow-up studies or when blinding is difficult or unethical (comparison of a surgical treatment and a medical treatment, for example).

******

ensaio clínicamente controlado (ECC)

Um estudo experimental no qual os investigadores comparam os desfechos obtidos num grupo de elementos que passaram pela intervenção com os desfechos dos elemento que tem características semelhantes, mas que não passaram pela intervenção. Nota:  nem todos os ensaios clínicos são randomizados, mas todos os ensaios randomizados são ensaios clínicos.

controlled clinical trial (CCT)

An experimental study in which the investigators compare the outcomes obtained in a group of subjects who have undergone an intervention with the outcomes in subjects who have similar characteristics, but have not undergone the intervention. Note: Not all clinical trials are randomized, but all randomized trials are clinical trials.

******

ensaio clínico

um estudo experimental rigoroso e controlado, que inclui elementos sadios e doentes, em que se deseja avaliar os desfechos de uma ou mais intervenções profiláticas terapêuticas. Nota: cada ensaio é projetado para responder questões científicas específicas. Em estudos experimentais (ensaios) a exposição a drogas, terapêuticas ou manobras preventivas são impostas pelo investigador. O investigador decide, através de algum método, incluir através de uma seleção randômica, quais elentos serão expostos; em estudos observacionais, a exposição é determinada pelo próprio elemento, naturalmente. Nota: a diferença entre um ensaio e um estudo é relativamente complexa, mas podem ser diferenciados da seguinte maneira; um ensaio suporta uma intervenção que poderá alterar o curso dos fatos e que se aplica a humanos, enquanto que um estudo examina os desfechos de uma intervenção ou da exposição a um dado fator, ou pode ter outros objetivos, tal como a observação do curso de uma doença. Um ensaio pode ser parte de um estudo, mas a recíproca não é verdadeira.

clinical trial

A rigourous and monitored experimental study* that includes healthy or ill human subjects and that is aimed at evaluating the outcomes of one or more prophylactic or therapeutic interventions. Note: Each trial is designed to answer specific scientific questions. In experimental studies (trials), exposure to a drug or to a therapeutic or preventive manoeuvre is imposed by the investigator. The investigator decides, through some method, including random selection, who will be exposed; in observational studies, whether there is exposure is determined by the subject himself/herself or naturally.
Note: The difference between a trial and a study is quite fuzzy, but they can be distinguished as follows: a trial bears on an intervention that will change the course of things and that applies to humans, while a study examines the outcomes of an intervention or of exposure to a given factor, or may have other aims, such as observing the course of a disease. A trial may be part of a study, but the reverse is not true.

******

ensaio controlado não randomizado

Um ensaio clínico no qual os indivíduos são divididos entre um grupo experimental e um grupo de controle, usando um método que não envolve randomização - com base nas restrições práticas dos investigadores, por exemplo - ou outros métodos tal como estabelecer tratamentos alternados. Outra forma de referência: ensaio controlado não-randomizado. 

nonrandomised controlled trial

A clinical trial in which the subjects are divided between an experimental group and a control group using a method that does not involve randomisation—on the basis of the investigators’ practical constraints, for example—or other methods, such as alternate assignment of treatments. Alternate spelling: non-randomized controlled trial

******

ensaio de cruzamento

Ensaio no qual os elementos recebem, em sequência, o tratamento (ou a intervenção de controle) e então, após um tempo especificado, a intervenção de controle (ou tratamento). Nota: neste tipo de estudo, os elementos fazem o controle de si mesmos e a randomização é usada para determinar a ordem pela qual um elemento recebe o tratamento ou a intervenção de controle. Períodos de lavagem são usualmente incluidos, desde que efeitos do primeiro tratamento possam permanecer ativos quando o segundo período for executado. (refresh?)

crossover trial

A trial in which the subjects receive, in sequence, the treatment (or control intervention), then, after a specified time, the control intervention (or treatment). Note: In this type of study, the subjects are their own controls, and randomisation is used to determine the order in which a subject receives the treatment and the control intervention. Washout periods are usually included, since otherwise the effects of the first treatment could carry over into the period when the second is given.

******

ensaio de grupo paralelo

Um ensaio que compara dois grupos contemporâneos, um recebendo o tratamento de interesse e outro sendo o grupo controle (num ensaio clínico randomizado, por exemplo). Nota: alguns desses ensaios tem mais do que um grupo de tratamento; outros comparam dois grupos de tratamento, cada um sendo o controle do outro.

parallel group trial

A trial that compares two contemporaneous groups, one receiving the treatment of interest, the other being the control group (in a randomised clinical trial, for example). Note: Some of these trials have more than one treatment group; others compare two treatment groups, each being a control for the other.

******

ensaio equivalente

Um ensaio com o objetivo primário de mostrar que a diferença entre respostas a duas ou mais intervenções é clinicamente insignificante. Nota: este objetivo é usualmente alcançado ao se demonstrar que a diferença real entre os tratamentos tende a ficar numa zona pré-determinada na qual os desfechos são considerados equivalentes.

equivalence trial

A trial with the primary objective of showing that the difference between the responses to two or more interventions is clinically insignificant. Note: This objective is usually achieved by demonstrating that the actual difference between the treatments is likely to fall within a pre-determined zone in which the outcomes are deemed clinically equivalent.

******

ensaio explanatório

Um ensaio que mede, em condições ideais, os efeitos de intervenções, usando cuidadosamente os sujeitos selecionados no estabelecimento de uma pesquisa clínica. Nota: este tipo de ensaio é frequentemente usado para avaliar a eficácia teórica de intervenções. Antônimo: ensaio pragmático.

explanatory trial

A trial that measures under ideal conditions the effects of interventions, using carefully selected subjects in a clinical research setting. Note: This type of trial is often used to evaluate the theoretical efficacy of interventions. Ant.: pragmatic trial

******

ensaio n de 1

Um ensaio clínico onde um único indivíduo é o total da população em estudo. Nota: a alocação randômica pode ser usada para determinar a ordem pela qual o indivíduo receberá a intervenção experimental e a experimentação de controle.

n of 1 trial

A clinical trial in which a single subject is the total population for the study. Note: Random allocation may be used to determine the order in which the subject will receive the experimental intervention and the control intervention.

******

ensaio pragmático

Um ensaio que mede o efeito de uma intervenção na prática da rotina clínica, para avaliar a efetividade real da intervenção. Antônimo: ensaio explanatório.

pragmatic trial

A trial that measures the effects of an intervention in routine clinical practice, to evaluate the intervention’s actual effectiveness. Ant.: explanatory trial.

******

ensaio sequencial

Um método estatístico que permite o encerramento de um experimento assim que for obtida uma resposta com a precisão desejada, com cada desfecho sendo examinado assim que ocorrer e sendo adicionado aos desfechos anteriores. Nota: as principais vantagens de um ensaio sequencial são: 1) é mais curtos do que um ensaio de duração fixa quando existe uma grande diferença na efetividade das intervenções sendo comparadas ou 2) um ensaio pode ser encerrado rapidamente quando existe um risco à saúde. Assim, com este enfoque, a atribuição dos tratamentos geralmente será conhecida antes do estudo, sendo requeridos métodos especiais para a análise e disseminação dos resultados internos. Conceito relacionado: meta análise.

sequential trial

A statistical method that allows for ending an experiment as soon as a response with the desired precision is obtained, with each outcome being examined as soon as it occurs and being added to all the previous outcomes. Note: The main advantage of a sequential trial is as follows: 1) it is shorter than a fixed-length trial when there is a large difference in the effectiveness of the interventions being compared; or 2) a trial can be terminated quickly when there is a health risk. Since, with this approach, the assignment of the treatments generally must be known before the study, special methods for the analysis and dissemination of interim results are required. Related concept: meta-analysis

******

ensaio simples em grande escala

Um ensaio randomizado, pragmático, caracterizado pelo recrutamento de um grande número de indivíduos, com amplos critérios para a inclusão de pacientes, múltiplos locais de estudo, um processo simplificado de coleta de dados e uso de registro eletrônico. Nota: os objetivos desse tipo de ensaio incluem a detecção de efeitos do tratamento pequenos ou moderados, pela obtenção de dados na efetividade prática do tratamento e pelo aumento da validade externa das descobertas.

large simple trial

A randomised pragmatic trial characterized by the recruitment of a large number of subjects, broad patient inclusion criteria, multiple study sites, a simplified data collection process and use of electronic registers. Note: The purposes of this type of trial include detecting small and moderate treatment effects, obtaining data on the practical effectiveness of the treatment and improving the external validity of the findings.

******

ensaio terapêutico

veja ensaio clínico.

therapeutic trial

See clinical trial.

******

ensaios clinícos randomizados

Um estudo comparando pelo menos duas intervenções, nas quais os participantes elegíveis são alocados aleatoriamente para o grupo de intervenção, ou grupos, e o grupo controle. Sigla: ECR. Nota 1: O controle pode ser uma prática padrão, um placebo, outra intervenção ativa ou nenhuma intervenção. Nota 2: Os participantes podem ser indivíduos ou grupos (por exemplo, unidade de randomização em um ensaio controlado randomizado em cluster). Ortografia alternativa: ensaio controlado randomizado

randomized controlled trials

A study comparing at least two interventions, in which the eligible participants are allocated randomly to the intervention group, or groups, and the control group. Acronym: RCT. Note 1: The control may be a standard practice, a placebo, other active intervention, or no intervention. Note 2: Participants may be individuals or groups (eg unit of randomization in a cluster randomized controlled trial). Alternate spelling: randomised controlled trial

******

epidemiologia

O estudo da distribuição e determinantes de estados relacionados à saúde ou eventos em populações especificadas.

epidemiology

The study of the distribution and determinants of health-related states or events in specified populations.

******

equidade

A alocação equitativa de recursos ou tratamentos entre distintos indivíduos ou grupos, de tal forma que cada um possui ou recebe o que deveria. Outra definição: o uso da alocação de recursos baseado no princípio da justiça distributiva. No entanto, a segunda definição envolve vários conceitos que definem essas regras com maior precisão (méerito, valor social, a maior contribuição, oportunidade equalitária, tratamento equalitário, oportunidade equalitária, prioridade ao que estiver em maior desvantagem, aposta padrão, etc.). Nota: equidade vertical significa que as pessoas com maior necessidade de serviços recebem a maioria desses serviços, enquanto que a equidade horizontal significa que pessoas com necessidades semelhantes recebem serviços semelhantes.

equity

The fair allocation of resources or treatments among different individuals or groups, such that they each get what they are owed or what they are entitled to. Other definition: The use of resource allocation rules based on the distributive justice principle. However, the latter involves various concepts that define these rules more precisely (merit, social value, the greater good, equal opportunity, equal treatment, priority to the most disadvantaged, standard gamble, etc.). Note: Vertical equity means that the people in the greatest need of services receive the most services, and horizontal equity means that people who have similar needs receive similar services.

******

equilíbrio

Um estado de genuina incerteza tal como saber qual de duas ou mais alternativas em tecnologia de saúde devem constituir o padrão de cuidados, considerando os benefícios e malefícios. Nota 1: Equipoise é largamente vista como necessária para um ensaio a ser justificado éticamente, especialmente quando os participantes são atribuidos a braços de ensaios randômicamente. Esta visão é sustentada pela idéia de que os pesquisadores médicos não podem  

equipoise

A state of genuine uncertainty as to which of two or more alternative health technologies should constitute the standard of care, considering benefits and harms. Note 1: Equipoise is widely viewed as necessary for a trial to be ethically justified, especially when participants are assigned to trial arms randomly. This view is underpinned by the idea that physician-researchers cannot waive their duty to act in the best interests of their patients. Note 2: As specified by the definition, equipoise usually refers to the state of uncertainty inhabited by the scientific and medical community, but it can also refer to the state of uncertainty inhabited by the researchers conducting a trial or by patients and the public.

******

equivalente em anos de saúde

O número hipotético de anos em saúde perfeita que podem ser considerados equivalentes ao número real de anos num estado de saúde imperfeito.

healthy-years equivalent (HYE)

The hypothetical number of years spent in perfect health which could be considered equivalent to the actual number of years spent in a defined imperfect state of health.

******

erro falso negativo

Em teste de hipóteses, um erro que ocorre quando se conclui incorretamente que a hipótese nula é verdadeira. Nota. Por exemplo, um erro do Tipo II é cometido se não se detectar diferença entre os desfechos de um grupo experimental e os do grupo de controle, quando de fato uma diferença existe. A probabilidade de se cometer esse tipo de erro é designada como beta (β). Sinônimo: erro do tipo II.

false negative error

Em teste de hipóteses, um erro que ocorre quando se conclui incorretamente que a hipótese nula é verdadeira. Nota. Por exemplo, um erro do Tipo II é cometido se não se detectar diferença entre os desfechos de um grupo experimental e os do grupo de controle, quando de fato uma diferença existe. A probabilidade de se cometer esse tipo de erro é designada como beta (β). Sinônimo: erro do tipo II.

******

erro falso positivo

Em teste de hipóteses, um erro que ocorre quando se conclui incorretamente que a hipótese nula é falsa. Nota. Por exemplo, um erro do Tipo I é cometido se for detectada uma diferença entre os desfechos de um grupo experimental e os do grupo de controle, quando de fato a diferença não existe.  A probabilidade de se cometer esse tipo de erro é designada como alfa (α). Sinônimo: erro do tipo I.

false positive error

In hypothesis testing, an error that occurs when it is incorrectly concluded that a null hypothesis is false. Note: For example, a Type I error is made if a difference is detected between the outcomes in an experimental group and those in a control group when in fact such a difference does not exist. The probability of making this type of error is designed as alpha (α). Syn.: Type I error.

******

erro na amostragem

Veja erro randômico.

sampling error

See random error.

******

erro randômico

Um desvio devido ao acaso entre a estimativa de um ponto e o valor do parâmetro estimado. Nota: erro randômico conduz a aproximadamente o mesmo número de resultados maiores do que o valor verdadeiro.

random error

A numerical value obtained in a sample and considered the best estimate of the population from which the sample is taken.

******

erro sistemático

Veja viés.

systematic error

See bias.

******

erro Tipo I

Veja alfa.

Type I error

See alpha.

******

erro Tipo II

Veja beta.

Type II error

See beta.

******

escolha informada

Uma escolha feita por pessoa competente com base na informação compreensiva relativa a uma intervenção, procedimento ou disponibilidade e qualidade de serviços de saúde.

informed choice

A choice made by a competent person on the basis of comprehensive information regarding an intervention, procedure, or the availability and quality of health services.

******

escolha pela chance

Um método de medida direta da utilidade de um estado da saúde, encontrado nos fundamentos do axioma de Neumann-Morgensten sobre a teoria da utilidade esperada. Nota: Um escore de utilidade é obtido estimando-se as probabilidades de que uma pessoa que foi solicitada a comparar duas opções, uma incerta (a de risco), e outra certa, não preferirá uma sobre a outra.

standard gamble (SG)

A method of directly measuring the utility of a health status, founded on the fundamental von Neumann-Morgenstern axioms of expected utility theory. Note: A utility score is obtained by estimating the probabilities that a person who is asked to compare two options, one uncertain (the gamble), the other certain, will not prefer one over the over.

******

escore da qualidade

Um valor atribuido à validade de um estudo, baseado tanto numa avaliação geral do mesmo ou em um ou mais critérios específicos (por exemplo, a ocultação da alocação). Nota: o escore da qualidade pode ser expresso em letras (A,B,C) ou números.

quality score

Um valor atribuido à validade de um estudo, baseado tanto numa avaliação geral do mesmo ou em um ou mais critérios específicos (por exemplo, a ocultação da alocação). Nota: o escore da qualidade pode ser expresso em letras (A,B,C) ou números.

******

especificidade

Uma característica de performance de um teste diagnóstico, definido como a proporção de pessoas que tiveram um resultado negativo no teste e as pessoas que não tiveram a doença; é calculada assim: verdadeiros negativos  ÷ (verdadeiros negativos + falsos positivos). Conceitos relacionados: acurácia, curva ROC e sensibilidade.

specificity

A characteristic of the performance of a diagnostic test, defined as the proportion of persons with a negative test result among persons who do not have the disease; it is calculated as follows: true negatives ÷ (true negatives + false positives). Related concepts: accuracy, ROC curve and sensitivity

******

estabelecimento de prioridade

A atribuição de uma ordem de prioridade baseada num critério explícito ou implícito para a seleção de tecnologias em saúde para avaliação.

priority setting

The assignment of an order of priority based on explicit or implicit criteria for selection of health technologies for assessment.

******

estado de saúde

O nível de saúde de uma pessoa, grupo ou população conforme a avaliação da própria pessoa ou através de medidas objetivas.

health status

The level of health of a person, group or population, as assessed by the person himself/herself or through objective measures.

******

estagiamento

A classificação da severidade de uma doença em estágios com base nos sinais, sintomas e testes paraclínicos.

staging

The classification of the severity of a disease in stages on the basis of the signs and symptoms and the paraclinical tests. 

******

Estatística Kappa

Uma medida do grau de acordo entre duas medidas da mesma variável categórica sobre e acima do acordo que foi devido apenas à probabilidade. Nota: o acordo entre dois avaliadores ou entre duas medidas de tempo para um avaliador podem ser medidas. 

Kappa statistic

A measure of the degree of agreement between two measures of the same categorical variable over and above the agreement that is due to chance alone. Note: The agreement between two raters or between two measurement times for one rater can be measured.

******

estimativa do efeito

Num estudo, a relação entre o desfecho observado quando a intervenção é aplicada e o desfecho observado num grupo de controle. Nota: esta relação pode ser expressa como um número que precisa ser tratado, relação de probabilidade, diferença de risco, risco relativo, média padronizada ou diferença ponderada da média ponderada. (conceito relacionado: efeito do tratamento).

estimate of effect

In a study, the relationship between the outcome observed when an intervention is applied and the outcome observed in a control group. Note: This relationship may be expressed as a number needed to treat, odds ratio, risk difference, relative risk, standardised mean difference or weighted mean difference. (Related concept: treatment effect)

******

estimativa pontual

Um valor numérico obtido numa amostra e considerado a melhor estimativa da população da qual a amostra foi tomada. Nota: por exemplo, x e s são estimativas pontuais de  µ e σ, que representam  a média e o desvio padrão. Um intervalo de confiança é tipicamente construído em torno da estimativa pontual. (conceito relacionado: intervalo de confiança).

point estimate

A numerical value obtained in a sample and considered the best estimate of the population from which the sample is taken. Note: For example, x and s are point estimates of µ and σ, which represent the mean and the standard deviation. A confidence interval is typically constructed around the point estimate. (Related concept: confidence interval)

******

estratégia de busca

A combinação de fontes, termos e limites usados numa pesquisa de literatura para identificar informação pertinente para revisão sistemática ou avaliação de tecnologia em saúde.

search strategy

The combination of sources, terms and limits used in a literature search to identify the pertinent information for a systematic review or health technology assessment.

estudo antes e depois

projeto de pesquisa onde um grupo de elementos é observado antes e depois da intervenção ou exposição a um dado fator.

before-and-after study

A research design where a group of subjects is observed before and after an intervention or exposure to a given factor.

******

estudo cross-seccional

Estudo observacional no qual os investigadores escolhem um grupo de elementos de uma dada população e medem presença simultânea ou ausência do fator de risco e do desfecho de interesse. Nota: a seleção do grupo de elementos é algumas vezes feita através de sorteio de amostragem aleatória.

cross-sectional study

An observational study in which the investigators choose a group of subjects in a given population and measure the simultaneous presence or absence of the risk factor and the outcome of interest. Note: The selection of the group of subjects is sometimes done through random sampling.

******

estudo de braço único

Numa análise ou avaliação de um estudo com apenas uma ramificação, isto é, um ensaio no qual não houve grupo para comparação paralela e todos os indivíduos receberam a mesma intervenção.

single-arm study

An analysis or evaluation of a study with only one branch, i.e. a trial in which there was no parallel comparison group and all the subjects received the same intervention. 

******

estudo de caso-controle

estudo observacional retrospectivo planejado para determinar se existe uma relação entre um dado parâmetro (Por xemplo: uma doença ou um determinante para a saúde) e uma causa especificada. Nota: investigadores selecionam um grupo de elementos apresentando o parâmetro de interesse (casos) e um grupo não apresentando  o parâmetro (controle). A seguir eles comparam os históricos dos casos e controles para determinar se existe uma associação entre o parâmetro e a causa sendo estudada. Nota: o termo "estudo de caso-controle" é frequentemente considerado, incorretamente, como sinônimo de "estudo retrospectivo". Embora, em ambos os casos, seja necessário olhar para o passado pela cadeia de eventos, o termo "estudo retrospectivo" não necessariamente inclui o elemento de comparação, que caracteriza os estudos de caso-controle. O qualificador "retrospectivo" simplesmente indica a direção temporal do estudo.

case-control study

A retrospective observational study designed to determine whether there is a link between a given parameter (e.g. a disease or a health determinant) and a specified cause. Note: Investigators select a group of subjects presenting the parameter of interest (cases) and a group not presenting the parameter (controls). Then they compare the histories of the cases and controls to determine whether there is an association between the parameter and the cause being studied. Note: The term “case-control study” is often, incorrectly, considered a synonym of “retrospective study.” Although, in both cases, it is necessary to look into the past for the chain of events, the term “retrospective study” does not necessarily include the element of comparison of two or more groups defined at the start of the study, an element that characterizes case-control studies. The qualifier “retrospective” simply indicates the temporal direction of the study.

******

estudo de coorte

estudo observacional no qual os parâmetros de um grupo de elementos expostos a um dado fator são comparados com aqueles de um grupo similar de elementos não expostos a esse fator. Nota: para que os grupos sejam comparáveis, os investigadores podem parear elementos exposto a um dado fator com outros não expostos ao fator com base em características comuns (Por exemplo: idade, sexo, severidade da doença) ou fazer os necessários ajustes estatísticos para obter, nos elementos pareados, características que sejam as mais similares possíveis. Outra definição: um estudo observacional no qual os investigadores selecionam e monitoram um grupo (coorte) de elementos expostos a um dado fator, para verificar os efeitos da exposição ao fator na saúde dos membros do coorte. Nota: este tipo de estudo é usualmente prospectivo, mas pode ser retrospectivo quando os dados já tiverem sido coletados. O importante é o ponto inicial: identificar os elementos expostos e não expostos a um dado fator e então determinar os efeitos da exposição na saúde.

cohort study

An observational study in which the parameters of a group of subjects exposed to a given factor are compared with those of a similar group of subjects not exposed to the factor. Note: To make the groups comparable, the investigators may match subjects exposed to a given factor with subjects not exposed to the factor on the basis of common characteristics (e.g. age, gender and disease severity) or may make the necessary statistical adjustments to obtain, in the matched subjects, characteristics that are as similar as possible. Other definition: An observational study in which the investigators select and monitor a group (cohort) of subjects exposed and non exposed to a given factor, to verify the effects of the exposure to the factor on the health of the cohort’s members. Note: This type of study is usually prospective, but may also be retrospective when the data have already been gathered. What is important is the starting point: identify the subjects exposed and not exposed to a given factor and then determine the health effects of the exposure.

******

estudo de intervenção

Veja ensaio clínico.

intervention study

See clinical trial.

******

estudo de prevalência

veja estudo transversal

prevalence study

See cross-sectional study.

******

estudo integrativo

Veja pesquisa secundária.

integrative study

See secondary research.

******

estudo não experimental

Um estudo baseado nas condições existentes de exposição a um dado fator, sem a intervenção do investigador. Nota: neste tipo de estudo, comumente usado, a evidência de uma relação causal entre a intervenção e o(s) desfecho(s) é relativamente fraca. (conceito relacionado: estudo observacional).

non-experimental study

A study based on the existing conditions of exposure to a given factor, without investigator intervention. Note: In this commonly used type of study, evidence of a causal link between the intervention and the outcome(s) of interest is relatively weak. (Related concept: observational study).

******

estudo negativo

Um estudo que não apresenta achados estatisticamente significativos, indicando que a intervenção sendo estudada provavelmente não tem um efeito com benefícios. Nota: este termo pode gerar confusão porque se refere tanto a significância etatística quanto à direção do efeito (positivo ou negativo). Como estudos analisam desfechos múltiplos, simultâneamente, o critério para a classificação de um estudo como "negativo" nem sempre é claro e, no caso de estudos de riscos ou de efeitos adversos, os estudos "negativos" são aqueles que não apresentam um efeito prejudicial. Antônimo: estudo positivo.

negative study

A study that does not have statistically significant findings, indicating that the intervention being studied probably does not have a beneficial effect. Note: This term can generate confusion because it refers both to statistical significance and the direction of effect (positive or negative). Since studies analyse multiple outcomes simultaneously, the criteria for classifying a study as “negative” are not always clear and, in the case of studies of risk or adverse effects, “negative” studies are ones that do not show a harmful effect. Ant.: positive study.

******

estudo observacional

Um estudo no qual os investigadores não intervém, somente observam os indivíduos que estão (e algumas vezes não estão, para a finalidade de comparação) expostos a um dado fator, e interpretam os desfechos. Nota: este tipo de estudo está mais sujeito a viéses do que um estudo experimental, tal como um ensaio controlado e randomizado. (conceito relacionado: estudo não experimental).

observational study

A study in which the investigators do not intervene, but only observe subjects who are (and sometimes who are not, for comparison purposes) exposed to a given factor, and interpret the outcomes. Note: This type of study is more subject to bias than is an experimental study such as a randomised controlled trial. (Related concept: non-experimental study.)

******

estudo positivo

Um estudo no qual foram obtidos resultados significantes, indicando que a intervenção sendo estudada provavelmente tem um efeito benéfico. Nota: este termo pode gerar confusão porque se refere tanto para a significância estatística quanto para a direção ou efeito. Como os estudos tem muitos indicadores de desfecho, o critério definindo um estudo "positivo" nem sempre fica claro e, no caso de estudos de um risco ou de efeitos adversos, por exemplo, estudos positivos são os que mostram um efeito danoso. Antônimo: estudo negativo.

positive study

A study that has obtained statistically significant results, indicating that the intervention being studied probably has a beneficial effect. Note: This term can generate confusion because it refers both to statistical significance and the direction of effect. Since studies often have many outcome indicators, the criteria defining a “positive” study are not always clear and, in the case of studies on a risk or given adverse effects, for example, positive studies are those that show a harmful effect. Ant.: negative study

******

estudo pré-teste/pós-teste

veja estudo pré e pós

pre-test/post-test study

See before-and-after study.

******

estudo prospectivo

Um estudo para avaliar os efeitos da exposição a uma dada intervenção ou fator, no qual os indivíduos são divididos em grupos que são expostos ou não expostos à intervenção ou fator de interesse, antes que os desfechos tenham ocorrido. Nota: ensaios randomizados controlados são sempre prospectivos, mas os estudos de caso-controle nunca são. Estudo de cohorte podem ser prospectivos ou retrospectivos. Conceito relacionado estudo retrospectivo.  † Um estudo de cohorte pode ser um estudo prospectivo, mas um estudo prospectivo não necessariamente é um estudo de cohorte: um estudo de coorte envolve uma metodologia, isto é, uma comparação que não é necessariamente comum a todos os estudos prospectivos. O qualificador "prospectivo", sem maiores detalhes, indica apenas a direção temporal do estudo.

prospective study

A study to evaluate the effects of exposure to a given intervention or factor, in which the subjects are divided into groups that are exposed or not exposed to the intervention or factor of interest before the outcomes have occurred. Note: Randomized controlled trials are always prospective, but case-control studies never are. Cohort studies may be prospective or retrospective. Related concept: cohort study; Ant.: retrospective study. † A cohort study may be a prospective study, but a prospective study is not necessarily a cohort study : a cohort study involves a methodology, i.e. comparison, that is not necessarily common to all prospective studies. The qualifier “prospective,” without further details, indicates only the study’s temporal direction.

******

estudo retrospectivo

Um estudo no qual os investigadores do desfecho pós-fato num grupo de indivíduos selecionados com base na sua exposição a uma  dada intervenção ou fator. Nota: este tipo de estudo está mais sujeito a viés do que um estudo prospectivo. Estudos de caso-controle são sempre retrospectivos, estudos de coorte às vezes são e ensaios randomizados controlados nunca são. Antônimo: estudo prospectivo.

retrospective study

A study in which the investigators do ex-post analysis of the outcomes in a group of subjects selected on the basis of their exposure to a given intervention or factor. Note: This type of study is more subject to bias than are prospective studies. Case-control studies are always retrospective, cohort studies sometimes are, and randomized controlled trials never are. Ant.: prospective study.

******

estudo sintético

Veja estudo secundário.

synthetic study

See secondary research.

******

estudos fase I, II II ou IV

Um sistema de codificação para as várias fases de ensaios clínicos de novas tecnologias. Nota: o sistema se aplica principalmente a drogas e dispositivos. Esses ensaios são parte do desenvolvimento e do processo de aprovação exigido por agências regulatórias. Ensaio Fase I: um ensaio envolvendo usualmente 20 a 80 voluntários para determinar a segurança de uma droga, a faixa segura de dosagem, absorção, atividade metabólica, excreção e duração da atividade. Ensaio Fase II: um ensaio controlado envolvendo 100 a 300 indivíduos para determinar a eficacia da droga e reações adversas à mesma (estes ensaios são às vezes divididos em ensaios piloto Fase IIa e ensaios bem controlados Fase IIb). Ensaio Fase III: um ensaio controlado grande, para determinar eficácia da droga e monitorar eventos adversos durante o uso de longo prazo (estes ensaios são às vezes divididos em ensaios Fase IIIa, conduzidos antes da aplicação autorizada por marketing, e ensaios Fase IIIb, conduidos após a aplicação autorizada por marketing, porém antes de sua aprovação). Ensaio Fase IV: um estudo de farmaco-vigilância, pós-marketing, para monitorar os efeitos de longo termo da droa e prover informação adicional sobre a segurança e eficácia da droga, incluindo grupos de pacientes com diferentes regimes de dosagem.

phase I, II, III or IV study

A codification system for the various phases of clinical trials of new technologies. Note: The system applies mainly to drugs and devices. These trials are part of the development and approval process required by regulatory agencies. Phase I trial: A trial usually involving 20 to 80 healthy volunteers to determine a drug’s safety, safe dosage range, absorption, metabolic activity, excretion and duration of activity. Phase II trial: 
A controlled trial involving 100 to 300 subjects to determine a drug’s efficacy and adverse reactions to the drug (these trials are sometimes divided into Phase IIa pilot trials and Phase IIb well-controlled trials). Phase III trial: 
A large controlled trial to determine a drug’s efficacy and monitor adverse events during longer-term use (these trials are sometimes divided into Phase IIIa trials, conducted before the marketing authorization application, and Phase IIIb trials, conducted after the marketing authorization application, but before approval). Phase IV trial: 
A post-marketing pharmacovigilance study to monitor a drug’s long-term effects and provide additional information on the drug’s safety and efficacy, including for patient groups with different dosing regimens.

******

ética

Uma teoria pretendendo determinar o que é bom, tanto para o indivíduo como para a sociedade como um todo. Outra definição: uma reflexão crítica sobre os desejos e fundamentos da ação humana (incluindo valores expressos) e um guia da conduta humana através do questionamento, discussão e a proposição de regras, ao invés da imposição de regras. Nota: à partir desta perspectiva, a ética se difere da moralidade, a qual é um sistema e a codificação de requisitos (padrão ou regras) governando a conduta humana, sendo os requisitos caracterizados pela sua universalidade e por um efeito restritivo. No entanto, a ética, moralidade e lei são proximamente interdependentes.

ethics

A theory aimed at determining what is good, both for the individual and for society as a whole. Other definition: A critical reflection on the aims and foundations of human action (including expressed values) and a guiding of human conduct through questioning, discussion and the proposing of guidelines, rather than the imposing of rules. Note: From this perspective, ethics differ from morality, which is a system and codification of requirements (standards and rules) governing human conduct, requirements characterised by their universality and by a restraining effect. Nonetheless, ethics, morality and law are closely interdependent.

******

EuroScan

A Rede Européia de Informação sobre Mudanças em Tecnologia da Saúde: http://www.euroscan.bham.ac.uk/. Uma rede de agências em avaliação de tecnologia da saúde que identifica e avalia tecnologias novas e emergentes.

EuroScan

The European Information Network on New and Changing Health Technologies http://www.euroscan.bham.ac.uk/.  A network of health technology assessment agencies that identify and assess new and emerging technologies.

******

evento adverso

qualquer alteração nociva, patológica ou não intencional numa função físca ou metabólica, revelada por sinais ou sintomas ou alteração de resultados de testes de laboratório, em qualquer fase de um estudo clínico, se ou não a alteração for considerada relacionada ao tratamento. Nota: ela pode envolver a exacerbação de uma condição pré-existente, distúrbios intercorrentes, um acidente, uma interação medicamentosa, ou ou significativa piora da doença.

adverse event

Any noxious, pathological or unintended change in a physical or metabolic function, revealed by signs or symptoms or a change in the results of laboratory tests, in any phase of a clinical study, whether or not the change is considered treatment-related. Note: It may involve the exacerbation of a pre-existing condition, intercurrent diseases, an accident, a drug interaction or a significant worsening of the disease.

******

exceção para dispositivo sob análise

Um processo regulatório e categoriação através do qual o FDA (Food and Drug Administration - Administração de Alimentos e Drogas, orgão norte-americano) autoriza o uso especificado de um dispositivo não autorizado, em configurações controladas, para a coleta de dados sobre a segurança do dispositivo e sobre a efetividade teórica e prática. Nota: os dados assim coletados podem ser utilizados em aplicações subsequentes e aprovadas de pré-marketing.

investigational device exemption (IDE)

A regulatory process and categorization whereby the United States Food and Drug Administration (FDA) authorizes specified use of an unapproved device in controlled settings for collecting data on the device’s safety and theoretical or practical effectiveness. Note: The data thus collected may be used subsequently in a premarketing approval application. 


******

exploração do horizonte

A identificação sistemática de tecnologias na saúde que são novas, emergentes ou tornando-se obsoletas, e que tem potencial de afetar a saúde, serviços de saúde e/ou a sociedade. Nota: 1: termos relacionados incluem aviso precoce e sistema de alerta.

horizon scanning

The systematic identification of health technologies that are new, emerging or becoming obsolete and that have the potential to effect health, health services and/or society. Note 1: Related terms include early awareness and alert system

******

extrapolação

Um cálculo, para valores de uma variável caindo fora das séries de variáveis observadas, os valores de uma função empiricamente conhecida e, por extensão, a predição resultante, dedução, previsão, transposição ou projeção.

extrapolation

A calculation, for values of the variable lying outside the series of observed variables, the values of an empirically known function and, by extension, the resulting prediction, deduction, forecasting, transposition or projection.


