# A {-}
abordagem em capital  humano

Um método para estimar os custos relacionados à perda de produção devida à doença. Nota: a estimativa é baseada no valor econômico para a sociedade da duração da vida saudável de uma pessoa de mesma idade e o valor econômico é medido pela estimativa da renda que pessoa poderia estar apta a obter.

human capital approach (HCA)

A method for estimating the costs related to loss of production due to illness. Note: The estimate is based on the economic value to society of the length of healthy life of a person the same age, and the economic value is measured by estimating the income that the person would have been able to earn.

******

ação de pesquisa

na pesquisa clínica: um processo  no qual um investigador identifica, analisa e corrige um problema, e então o reacessa, se necessário, iniciando o processo novamente, até o problema ser resolvido completamente. Na pesquisa social: um método de pesquisa para a resolução de um problema num dado contexto, através de uma investigação democrática na qual os investigadores trabalham com os atores locais na busca e aplicação de soluções para um problema que seja de importância significativa para a comunidade.

action research

In clinical research: a process in which an investigator identifies, analyses and corrects a problem, then reassesses it and, if necessary, begins the process over again, until the problem is completely resolved. In social research: a research method for resolving a problem in a given context through a democratic investigation in which the investigators work with the local actors to seek and apply solutions to a problem that is of major importance to the community.

*****
aceitabilidade do custo-efetividade

Curva que ilustra a probabilidade de uma dada opção ser eficiente com base no valor atribuido a um ano de vida adicional de qualidade ajustada (QALY).

cost-effectiveness acceptability (CEA)

A curve illustrating the probability that a given option is efficient on the basis of the value assigned to an additional quality-adjusted life year (QALY).

******

acesso

é o grau ao qual um paciente está apto a obter cuidados ou serviços, considerando-se restrições financeiras e organizacionais dos sistemas de saúde.

access

The degree to which a patient or group is able to obtain care or services, taking into account the health system’s financial and organizational constraints.

******

acurácia

1) no contexto de um estudo, é a qualidade de uma medida (por exemplo, a estimativa média do efeito de um tratamento) que é correta ou que reflete a real efetividade do tratamento; não confundir com precisão: uma estimativa pode ser acurada, embora não precisa, se for baseada num método não tendencioso que mostre grandes variações aleatórias (severidade da doença, condições coexistentes). 2) no contexto de um teste diagnóstico, é a proporção na qual os resultados correspondem àqueles do teste de referência adotado (i.e. a soma do verdadeiros positivos com a soma dos verdadeiros negativos, dividida pelo tamanho da amostra estudada).

accuracy

1) In the context of a study, the quality of a measurement (e.g. the mean estimate of a treatment effect) that is correct or that reflects the actual effectiveness of the treatment.Note: Not to be confused with preciseness: an estimate can be accurate, yet not be precise, if it is based on an unbiased method that shows great random variations (severity of the disease, coexisting conditions). 2) In the context of a diagnostic test, the proportion in which the results correspond to those of the chosen refererence test, i.e. the sum of the true positives and the true negatives, divided by the size of the sample of the population studied.

******

acurácia diagnóstica

vide acurácia

diagnostic accuracy

see accuracy

******

aderência

1) em pesquisa, é a medida da extensão à qual os elementos passam numa dada intervenção. Nota: pode ser a extensão à qual os elementos aderem com relação à terapia medicamentosa, passam pela prescrição médica ou procedimento cirúrgico, executam um determinado regime de exercícios, se abstém de fumar, etc. 2) para investigadores, o fato de seguir um protocolo de pesquisa 3) na definição de parâmetros clínicos, os elementos que se supõe seguir um tratamento ou aqueles registrados num programa, pelo fato de aderirem com os requisitos do tratamento ou do programa. Nota: como esta palavra tem esses 3 significados, para evitar qualquer confusão, é melhor referir-se a "aderência a um protocolo de pesquisa" quando se quiser indicar a aderência do investigador.

compliance

1) In research, a measure of the extent to which the subjects undergo an assigned intervention. Note: It may be the extent to which the subjects comply with the drug therapy, undergo the prescribed medical or surgical procedure, do the prescribed exercise regimen, abstain from smoking, etc. 2) For investigators, the fact of following a research protocol. 3) In a clinical setting, for subjects who are supposed to undergo a treatment or who are registered in a program, the fact of complying with the requirements of that treatment or program. Note: Since this word has these three meanings, to avoid any confusion, it might be better to refer to “compliance with the research protocol” when what is meant is the investigator’s compliance.

******

advogado do consumidor

Pessoa ou organização que está ativamente envolvida com terceiros e que apresenta as perspectivas e preocupações de um grupo de pacientes.

consumer advocate

A person or organisation who/that is actively involved with others and presents the perspectives and concerns of a group of patients.

******

alfa

em teste de hipóteses, a probabilidade de erro do Tipo I, i.e. a probabilidade de se concluir incorretamente que a hipótese nula é falsa. Nota: por exemplo, alfa poderia ser a probabilidade de se concluir que uma intervenção é efetiva quando ela não tem um efeito verdadeiro. Se os investigadores definirem alfa como 0.05, isso significa que eles aceitam 5% de risco de um erro do Tipo I. O valor de alfa é comumente definido como 0.01, 0.05 ou 0.10.

alfa

In hypothesis testing, the probability of a Type I error, i.e. the probability of concluding incorrectly that a null hypothesis is false. Note: For example, α could be the probability of concluding that an intervention is effective when it has no true effect. If the investigators set α at 0.05, this means that they accept that there is a 5% risk of a Type I error. The α-level is commonly set at 0.01, 0.05 or 0.10.

******

alocação do tratamento

veja randomização

treatment allocation

See randomization

******

alocação não estritamente randômica

veja ocultação da alocação. 

quasi random allocation

See concealment of allocation. Alternate spellings: quasi-random allocation, quasirandom allocation.

******

alvo móvel

Um assunto de avaliação (uma tecnologia, por exemplo) que é difícil de definir porque está mudando rapidamente.

moving target

A subject of evaluation (a technology, for example) that is difficult to define because it is changing rapidly.

******

amostragem randomizada

Um método de obtenção de uma mostra representativa de uma população.

random sampling

A method of obtaining a representative sample of a population.

******

análise Bayesiana

método estatístico que explicitamente inclui uma distribuição de  probabilidades anterior, baseada numa opinião subjetiva ou numa evidência objetiva, tal como os resultados de uma pesquisa anterior.

Bayesian analysis

A statistical method that explicitly includes a prior probability distribution based on a subjective opinion or objective evidence, such as the results of previous research. 

******

análise da intenção-para-tratar
Uma análise na qual os efeitos observados nos indivíduos de um ensaio são avaliados de acordo com a intervenção para a qual foram randomizados, se eles a receberam ou não e se eles concordaram  ou não com o protocolo do estudo. Nota: este tipo de análise é favorecido, porque mantém a equivalência dos grupos randomizados. Além disso, na avaliação da efetividade prática de uma intervenção, ela espelha a não aderência e as alterações de tratamento que normalmente ocorrem na prática. Conceito relacionado: por protocolo.

intention-to-treat (ITT) analysis

An analysis in which the effects observed in the subjects of a trial are evaluated according to the intervention to which they were randomised, whether or not they received it, or whether or not they complied with the study protocol. Note: This type of analysis is favoured because it maintains the equivalence of the randomised groups. Also, in the evaluation of the practical effectiveness of an intervention, it mirrors the non-compliance and the treatment changes likely to occur in practice. (Related concept): per protocol

******

análise da minimização de custo

Avaliação econômica consistindo na comparação dos custos de várias opções presumidas para produzir desfechos equivalentes e para se determinar, destas, a opção de menor custo.

cost-minimization analysis (CMA)

An economic evaluation consisting of comparing the costs of various options presumed to produce equivalent outcomes and determining the least costly of those options.

******

análise de custo-beneficio

Avaliação econômica que consiste na comparação de várias opções, nas quais os custos e desfechos são quantificados em unidades monetárias comuns.

cost-benefit analysis

An economic evaluation consisting of comparing various options, in which costs and outcomes are quantified in common monetary units.

******

análise de custo-consequência

Avaliação econômica consistindo na comparação de várias opções, nas quais o custo dos componentes e os vários desfechos de uma doença ou intervenção são calculados e apresentados separadamente.

cost-consequent analysis (CCA)

An economic evaluation consisting of comparing various options, in which the cost components and the various outcomes of a disease or intervention are calculated and presented separately.

******

análise de custo-utilidade

Avaliação econômica consistindo na comparação de várias opções, nas quais os custos são medidos em unidades monetárias e os desefechos são medidos em unidades de medida de utilidade, usualmente em termos da utilidade para o paciente (usando anos de vida com a qualidade ajustada, por exemplo). Nota: esta é uma forma de análise de custo-efetividade na qual uma opção é ajustada com base na qualidade de vida.

cost-utility analysis (CUA)

An economic evaluation consisting of comparing various options, in which costs are measured in monetary units and outcomes are measured in utility units, usually in terms of utility to the patient (using quality-adjusted life years, for example). Note: This is a form of cost-effectiveness analysis in which the effectiveness of an option is adjusted on the basis of quality of life.

******

análise de impacto

Uma avaliação de efeitos de um relatório de avaliação de tecnologia em saúde ou de um serviço ou programa de saúde.

impact analysis

An evaluation of the effects of a health technology assessment report or of a health service or programme.

******

análise de regressão

Um método consistindo na seleção de um modelo matemático (regressão linear ou regressão logística, por exemplo) para descrever ou predizer o efeito de uma ou mais variáveis independentes X numa variável dependente Y. Nota: os termos são assim usados: regressão liner quando a variável Y é continua, regressão logística quando Y é uma variável dicotômica, regressão simples quando existe uma variável única X, e regressão múltipla quando existem várias variáveis X.

regression analysis

A method consisting of selecting a mathematical model (linear or logistic regression, for example) that explains the data to describe or predict the effect of one or more independent variables X on a dependent variable Y. Note: The terms are used as follows: linear regression when the variable Y is continuous, logistic regression when Y is a dichotomous variable, simple regression when there is a single variable X, and multiple regression when there are several variables X.

******

análise de sensibilidade

Um meio para se avaliar a robustez de um modelo matemático pelo teste da variação plausível das estimativas das varíáveis-chave independentes,  para determinar se tais variações resultam em alterações significativas nos resultados dos modelos. Nota: a análise de sensibilidade também pode ser usada para outros estudos, tais como análises de ensaios clínicos, para determinar se a inclusão ou exclusão de certos dados altera os resultados, e em meta análise, para determinar se a inclusão ou exclusão de certos estudos alteram os resultados.

sensitivity analysis

A means for evaluating the robustness of a mathematical model by testing a plausible range of estimates of key independent variables to determine whether such variations result in meaningful changes in the model’s results. Note: Sensitivity analysis can also be used for other study types, such as clinical trials analysis, to determine whether inclusion or exclusion of certain data changes the results, and meta-analysis, to determine whether inclusion or exclusion of certain studies changes the results.

******

análise do custo da doença

Avaliação do impacto financeiro geral na sociedade de uma dada doença ou problema de saúde. Nota: a soma, expressa em unidades monetárias, inclui custos de tratamento, mas não inclui os benefícios dos tratamentos ou dos desfechos.

cost-of-illness analysis

An evaluation of the overall economic impact on society of a given disease or health problem. Note: The sum, expressed in monetary units, includes treatment costs, but not treatment benefits or outcomes.

******

análise do impacto do orçamento

avaliação do impacto financeiro pela introdução de uma tecnologia ou de um serviço nos orçamentos de capital e operacional de um governo ou agência.

budget impact analysis

An evaluation of the financial impact of the introduction of a technology or service on the capital and operating budgets of a government or agency.

******

análise do subgrupo

Uma técnica consistindo na análise de dados de um subgrupo separadamente daqueles da população geral sendo estudada. Nota: esse tipo de análise pode ser planejado antecipadamente no protocolo de pesquisa, e os resultados que ele provê podem ser considerados apenas exploratórios. Qualquer efeito significativo observado num subgrupo deverá ser verificado em outros estudos. Conceito relacionado: teste múltiplo.

subgroup analysis

A technique consisting of analysing the data from a subgroup separately from those from the overall population studied. Note: This type of analysis should be planned beforehand in the research protocol, and the results it provides are to be considered exploratory only. Any significant effect observed in a subgroup must be verified in other studies. Related concept: multiple testing.

******

análise interna

Uma análise realizada durante um estudo para comparar os grupos experimentais com relação à efetividade ou segurança de uma intervenção, quando a situação requer. Nota: análises internas devem ser planejadas no protocolo (seu númerom o tempo de sua aplicação, os critérios subjacentes, etc.). Elas diferem da análise padrão que é relaizada ao final do período de seguimento provido pelo protocolo do estudo. O número de indivíduos num estudo deve refletir o número planejado de análises internas.

interim analysis

An analysis performed during a study to compare the experimental groups with regard to the effectiveness or safety of an intervention, when the situation requires.Note: Interim analyses must be planned in the protocol (their number, the time of their application, the criteria underlying them, etc.). They differ from the standard analysis, which is performed at the end of the follow-up period provided for in the study protocol. The number of subjects in a study must reflect the planned number of interim analyses. 

******

ano de vida ajustado pela qualidade (QALY)

Uma unidade de desfecho de uma intervenção onde são ganhos (ou perdidos) anos de vida posteriores a essa intervenção, ajustados com base na qualidade de vida durante esses anos. Nota: esse parâmetro pode prover uma unidade comum para comparação de custo-utilidade através de diferentes intervenções e problemas de saúde. O DALY (ano de vida ajustado pela incapacidade) e o HYE (anos saudáveis equivalentes) são unidades análogas ao QALY.

quality-adjusted life year (QALY)

A unit of outcome of an intervention where gains (or losses) of years of life subsequent to this intervention are adjusted on the basis of the quality of life during those years. Note: This parameter can provide a common unit for comparing cost-utility across different interventions and health problems. Disability-adjusted life year (DALY) and healthy-years equivalent (HYE) are QALY-analogous units.

******

ano de vida com deficiência ajustada (DALY)

Uma unidade de estado de saúde onde a expectativa de vida, de acordo com a idade, é ajustada pela perda de saúde e anos de vida devidos à deficiência ou à lesão. Nota: esta medida é frequentemente utilizada para estabelecer a incidência global de uma moléstia (para uma grande população).

disability-adjusted life year (DALY)

A unit of health status where life expectancy according to age is adjusted by the loss of health and years of life due to disability from disease or injury. Note: This measurement is often used to assess the overall burden of disease (for a large population).

******

ano fiscal

Um período, geralmente de um ano, após o qual uma entidade prossegue com o encerramento das suas contas e a definição de suas demonstrações  financeiras anuais.

FY

A period, generally one year, at the end of which an entity proceeds with the closing of its accounts and the establishment of its annual financial statements.

******

anualização

método para converter o custo do capital no custo equivalente anual, calculado com base na vida útil, custo inicial (custo de aquisição) e valor no final da vida útil de um equipamento, e as taxas de juros sobre o capital investido. Nota: este método também pode ser aplicado no cálculo da renda.

annualisation

A method for converting capital cost into an equivalent annual cost, calculated on the basis of the lifespan, initial cost (acquisition cost) and end-of-lifespan value of the equipment, and the interest rates on the invested capital.Note: This method can also be applied to income.

******

Aplicabilidade

a possibilidade de aplicar em outros contextos os resultados de uma observação ou estudo.

applicability

The possibility of applying in other settings the results of an observation or study.

******

aplicação com a aprovação de pre-marketing 

Uma aplicação feita pelo fabricante ao FDA (Food and Drug Administration) para aprovação de fornecer ao mercado um produto médico, nos Estados Unidos. Nota: esta aplicação inclui a informação pertinente documentando a segurança e a efetividade do produto. Sinônimo: aplicação com a aprovação de pré-mercado

premarketing approval application (PMA)

An application made by the manufacturer to the Food and Drug Administration (FDA) for approval to market a medical product in the United States. Note: This application includes the pertinent information documenting the safety and effectiveness of the product. Alternative spellings: pre-market approval application, premarket approval application

******

aplicação de nova droga sob análise

Uma aplicação para a aprovação de uma droga não aprovada ou de uma droga previamente aprovada para outro uso, submetida pelo fabricante ao FDA (Unites States Food and Drug Administration -  Administração de Alimentos e Drogas norte-americano) antes do teste dessa droga em humanos . Outra definição: um arquivo fornecido às autoridades competentes por um fabricante para obter a notificação de aprovação para uma nova droga e que contém as fases I, I e II dos ensaios clínicos. Nota: o termo "submissão de nova droga" é usado no Canadá e o termo "aplicação de nova droga" é usado nos Estados Unidos.

new drug application (NDA)

An application submitted by a manufacturer to the Food and Drug Administration (FDA) for approval to market a new drug (a new, non-biological molecular entity) for human use. Other definition: A file that is submitted to the competent authorities by a manufacturer to obtain a notice of compliance for a new drug and that contains phases I, II and III clinical trials. Note: The term new drug submission is used in Canada and the term new drug application is used in the United States.

******

Auditoria

ferramenta para a medida da aderência a padrões pré-estabelecidos, para a identificação de boas e más práticas. Nota: em alguns casos, a auditoria pode incluir a definição de padrões.

Audit

A tool for measuring compliance with pre-determined standards, to identify good and bad practices. Note: In some cases, the audit may include standard setting.

******

Autonomia

O princípio do direito à auto-determinação, i.e. o direito dos pacientes de tomar suas próprias decisões à respeito de cuidados médicos. Nota: autonomia implica que as pessoas são livres e aptas a tomas decisões que as afetem com base em seu próprio sistema de valores e crenças

autonomy

The principle of the right of self-determination, i.e. patients’ right to make their own decisions regarding medical care. Note: Autonomy implies that people are free and able to make the decisions that affect them on the basis of their own system of values and beliefs.

******

Avaliação

processo científico usado para descrever e analisar as propriedades de uma tecnologia da saúde - sua segurança, eficácia, aplicabilidade e indicações de uso, custo e custo - efetividade, bem como as consequências sociais, econômicas e éticas

assessment

A scientific process used to describe and analyse the properties of a health technology—its safety, efficacy, feasibility and indications for use, cost and cost-effectiveness, as well as social, economic and ethical consequences.

******

avaliação crítica

Processo de se estabelecer e interpretar  resultados de pesquisas científicas, sistematicamente analisando sua validade, sua significância estatística e sua relevância clínica 

critical appraisal

The process of assessing and interpreting scientific research results by systematically analysing their validity, clinical and statistical significance, and clinical relevance.

******

avaliação da qualidade

Atividades de medida e monitoramento para se determinar o quão bem o cuidado com a saúde é entregue, com referência aos padrões aplicáveis ou limites aceitáveis de cuidados. (Conceitos relacionados: garantia da qualidade e cuidado com a qualidade)

quality assessment

The measurement and monitoring activities for determining how well health care is delivered with reference to the applicable standards or acceptable bounds of care.(Related concepts: quality assurance and quality of care.)

******

avaliação de campo

Um estudo projetado expressamente para coletar dados originais de uma tecnologia promissora, para verificar sua efetitividade prática, quando não há evidência suficiente para se tomar uma decisão baseada em informações.

field evaluation

A study designed expressly to collect original data on a promising technology to verify its practical effectiveness when there is insufficient evidence to make an informed decision.

******

avaliação de necessidades de saúde

Uma avaliação das necessidades de saúde da comunidade e o uso dessa informação para estabelecer prioridades e planejar a entrega e os serviços de cuidado com a saúde.

health needs assessment

An assessment of a community’s health needs and the use of this information to set priorities and plan health care delivery and services.

******

avaliação de pesquisa

Um campo de questões que avalia a operação, processos, desfechos e utilidade de estruturas organizacionais (programas, agências, políticas, etc..).

evaluation research
A field of inquiry that assesses the operation, processes, outcomes and utility of organizational structures (programme, agency, policy, etc.).

******

avaliação de risco

A estimativa qualitativa ou quantitativa da verosimilhança de um evento adverso que possa resultar da exposição a um dado fator de risco ou da ausência de condições benéficas.

risk assessment

The qualitative or quantitative estimation of the likelihood of an adverse event that may result from exposure to a given risk factor or the absence of beneficial conditions. 

******

avaliação de tecnologia

Veja avaliação de tecnologia em saúde

technology assessment

See health technology assessment.

******

Avaliação de tecnologia da saúde (ATS)

A avaliação sistemática das propriedades e efeitos da tecnologia na saúde, endereçando os efeitos diretos e intencionais dessa tecnologias, bem como as consequências indiretas e não intencionais, com o objetivo principal de informar a tomada de decisão relacionada a essa tecnologia. Nota: ATS é conduzida por grupos interdisciplinares que usam gabaritos analíticos explícitos numa variedade de métodos.

healt technology assessment (HTA)

The systematic evaluation of the properties and effects of a health technology, addressing the direct and intended effects of this technology, as well as its indirect and unintended consequences, and aimed mainly at informing decision making regarding health technologies. Note: HTA is conducted by interdisciplinary groups that use explicit analytical frameworks drawing on a variety of methods.

******

Avaliação de Tecnologia em Saúde Internacional

HTAi (Avaliação de Tecnologia em Saúde Internacional) - uma sociedade internacional focada na avaliação de tecnologia em saúde que congrega instituições acadêmicas, instituições de cuidados com a saúde, indústria, negócios, o setor de voluntariado e o setor público.

HTAi

Health Technology Assessment International - an international society focussed on health technology assessment that brings together academic institutions, health care institutions, industry, business, the voluntary sector and the public sector.

******

avaliação econômica

A análise comparativa dos custos e consequências de duas ou mais opções possíveis. Nota: dependendo das consequências serem expressas como variáveis monetárias, físicas ou qualitativas, a análise poderá ser, respectivamente, de custo-benefício, de custo-efetividade ou de custo-utilidade.

economic  evaluation

The comparative analysis of the costs and consequences of two or more possible options. Note: Depending on whether the consequences are expressed as monetary, physical or qualitative variables, the analysis may be a cost-benefit, cost-effectiveness or cost-utility analysis.
