# I {-}

impacto diagnóstico

Uma medida de utilidade de resultados de testes na elaboração de um diagnóstico. Nota: este conceito é usado relativamente pouco.

diagnostic impact

A measurement of the usefulness of test results for making a diagnosis. Note: This concept is used relatively little.

******

impacto terapêutico

Uma característica de eficácia do teste diagnóstico que descreve o efeito de um teste diagnóstico em opções de tratamento.

therapeutic impact

A characteristic of diagnostic test efficacy that describes the effect of a diagnostic test on treatment choices.

******

imperativo tecnológico

A inclinação em usar uma tecnologia que tenha potencial para proporcionar algum benefício, seja marginal ou infundado, baseada numa permanente fascinação pela tecnologia, pela expectativa de que o novo é melhor, e por outros incentivos financeiros ou profissionais.

technological imperative

The inclination to use a technology that has potential for some benefit, however marginal or unsubstantiated, based on an abiding fascination with technology, the expectation that new is better, and financial and other professional incentives.

******

INAHTA

International Network of Agencies for Health Technology (INAHTA); Rede Internacional de Agências para Avaliação de Tecnologias em Saúde; Uma associação internacional sem fins lucrativos de agências de avaliação de tecnologia em saúde, representando mais de 40 agências no mundo todo. (http://www.inahta.net).

INAHTA

International Network of Agencies for Health Technology (INAHTA); An international non-profit association of health technology assessment agencies, representing over 40 agencies worldwide (http://www.inahta.net ).

******

incidência

O número de novos casos de uma doença ou condição numa população em risco num dado período, normalmente de um ano. 

incidence

The number of new cases of a disease or condition in a population at risk over a given period, usually one year.

******

Index Medicus

Uma lista bibliográfica de referências a artigos biomédicos de periódicos do mundo todo. O Index Medicus deixou de existir em dezembro de 2004 e foi o equivalente impresso da base de dados MEDLINE. 

Index Medicus

A bibliographic listing of references to articles from biomedical journals worldwide. Note: Index Medicus ceased to exist in December 2004. It was the print equivalent of the MEDLINE database. 

******

indicação

Um sintoma clínico, fator de risco ou circunstância para os quais o uso de uma particular intervenção poderia ser adequada, como recomendado numa guia ou protocolo de prática médica de cuidados, ou por um corpo regulatório ou outra fonte de autoridade. 

indication

A clinical symptom, risk factor or circumstance for which the use of a particular intervention would be appropriate, as recommended in a clinical practice guideline or protocol of care, or by a regulatory body or other authoritative source.

******

Índice de Utilidades na Saúde

(http://www.fhs.mcmaster.ca/hug/). Um sistema genérico e completo de pontuação, baseado nas preferências de vários usuários e projetado para medir o estado da saúde e a qualidade de vida, e para produzir pontuações sobre utilidade.

Health Utilities Index (HUI)

(http://www.fhs.mcmaster.ca/hug/).  A generic and complete scoring system based on various users’ preferences and designed to measure health status and quality of life and to produce utility scores.

******

intermediação de conhecimentos

Uma atividade de transferência de conhecimento na qual uma terceira parte faz a ligação entre pesquisadores e os usuários dos pesquisadores, para facilitar a formação de redes de relacionamento e a troca de informações, difusão, inovação e suporte mútuo.

knowledge brokering

A knowledge-transfer activity in which a third party liaises between researchers and research users to facilitate networking and information exchange, diffusion of innovation and mutual support.

******

intervalo de confiança (IC)

intervalo de valores acima e abaixo do ponto estimado com uma dada probabilidade de incluir o valor verdadeiro de um dado parâmetro, tal como o efeito de um tratamento. Nota: o intervalo de confiança é a área de incerteza na estimativa de um parâmetro. O uso desse intervalo reflete o fato de que o estudo provê uma estimativa do parâmetro, fora das muitas estimativas que seriam possíveis se o estudo fosse repetido diversas vezes. Se um IC de x% for construido a cada repetição, x% dos intervaos conterão o valor verdadeiro do parâmetro. Investigadores frequentemente usam intervalos de confiança de 90%, 95% ou 99%. Assim, um IC de 95% indica que há 95% de probabilidade do intervalo de confiança , calculado num estudo em particular, incluir o valor verdadeiro do parâmetro. Se o intervalo incluir o valor nulo (uma diferença de zero, em média, um risco relativo ou razão de chances de 1, ou um coeficiente de correlação de zero, por exemplo), a hipótese nula não poderá ser rejeitada. Um intervalo de confiança mais estreito ao redor de um ponto estimado indica uma estimativa mais precisa do que um intervalo de confiança mais amplo.

confidence interval (CI)

A range of values below and above the point estimate that has a given probability of including the true value of a given parameter, such as a treatment effect. Note: The confidence interval is the area of uncertainty for the estimating of a parameter. The use of this interval reflects the fact that a study provides one estimate of a parameter, out of the many estimates that would be possible if the study were repeated several times. If an X% CI is constructed for each repetition, X% of the intervals will contain the true value of the parameter. Investigators typically use confidence intervals of 90%, 95% or 99%. Thus, a 95% confidence interval indicates that there is a 95% probability that the confidence interval calculated from a particular study includes the true value of the parameter. If the interval includes a null value (a difference in means of 0, an odds ratio or a relative risk of 1, or a correlation coefficient of 0, for example), the null hypothesis cannot be rejected. A narrow confidence interval around a point estimate indicates a more precise estimate than a wide confidence interval.

******

intervalo de credibilidade

Faixa de valores ao redor de uma estimativa central de um parâmetro, construida usando métodos Bayesianos. Nota: o intervalo de credibilidade é o equivalente ao intervalo de confiança Bayesiano, mas a interpretação é ligeriamente diferente: a probabilidade que um parâmetro esteja em um intervalo de credibilidade de X% é X/100. Por exemplo, um intervalo de credibilidade de 95% (0.83-1.36) para uma razão de chances para mortalidade, significa que existe uma probabilidade de 0.95 de que a razão de chance da popilação esteja entre 0.82 e 1.36.

credible interval

A range of values around the central estimate of a parameter, constructed using Bayesian methods. Note: The credible interval is the Bayesian equivalent of a confidence interval, but the interpretation of it is slightly different: the probability that a parameter is in an X% credible interval is X/100. For example, a 95% credible interval (0.82-1.36) for an odds ratio for mortality means that there is a 0.95 probability that the odds ratio in the population is between 0.82 and 1.36.

******

ISTAHC - International Society of Technology Assessment in Health Care (ISTAHC)


A primeira associação dos envolvidos em avaliação de tecnologia em saúde. A sociedade funcionou por cerca de vinte anos até ser dissolvida ao redor de 2002. Nota: ISTAHC foi substituida pela HTAi.

ISTAHC - International Society of Technology Assessment in Health Care (ISTAHC)
The first international association for those involved in health technology assessment. The society operated for nearly twenty years, until it was disbanded around 2002. Note: ISTAHC was replaced by HTAi. 
