# C {-}

cadeia de Monte Carlo / Markov (MCMC)

Um método de análise probabilística combinado com o modelo de Markov, que captura as probabilidades transacionais entre vários estados do estudo da interação entre as distribuições de probabilidade relacionadas a cada variável. Nota: este tipo de simulação proporciona uma estimativa do grau de incerteza de um modelo. É largamente utilizado na análise Bayesiana, na construção ou na atualização de modelos de distribuição conjunta de variáveis. 

Markov chain Monte Carlo (MCMC)

A probabilistic analysis method combined with the Markov model, which captures the transitional probabilities between various states to study the interaction between the probability distributions attached to each variable. Note: This type of simulation provides an estimate of the degree of uncertainty in a model. It is widely used in Bayesian analysis to build or update models of the joint distribution of variables.

******

Caso

em epidemiologia, a pessoa com a doença ou característica de interesse para um ensaio clínico.

Case

In epidemiology, a person with the disease or characteristic of interest in a clinical trial.

******

causalidade

causas relacionadas e os efeitos por elas produzido. Nota: os critériosde Bradford Hill para associação causal são: consistência; força; especificidade; relação dose/resposta; relação temporal (a exposição sempre antecede o desfecho; este é o único critério essencial); plausibilidade biológica; coerência e experimento.

causality

The relating of causes to the effects they produce. Note: The Bradford Hill criteria for causal association are: consistency; strength; specificity; dose–response relationship; temporal relationship (exposure always precedes the outcome; it is the only essential criterion); biological plausibility; coherence; and experiment.

******

CDMR - base de dados de revisões metodológicas

veja a metodologia de registro Cochrane.

Cochrane database of methodology reviews (CDMR)

See Cochrane Methodology Register.

******

CDSR - base de dados de revisões sistemáticas da Cochrane

base de dados composta de textos completos de todas as revisões sistemáticas e de todos os projetos de revisões sistemáticas (protocolos) da  "Cochrane Collaboration" (cooperação Cochrane).

Cochrane database od systematic reviews (CDSR)

A database composed of the full text of all Cochrane Collaboration systematic reviews and systematic review projects (protocols).

******

cegamento

num ensaio clínico, a ocultação dos elementos e/ou investigadores da identidade das pessoas recebendo as intervenções em estudo e as intervenções de controle (ou cuidados-padrão). Nota: a intenção deste método é eliminar a possibilidade de que o conhecimento da intervenção sendo ministrada aos pacientes possa afetar o desfecho ouque  o comportamento do investigador  possa afetar o desfecho. Nem sempre o cegamento é prático (Por exemplo, ao comparar uma cirurgia com um tratamento medicamentoso), mas deveria ser usado sempre que possível quando compatível com a otimização do cuidado ao paciente.

blinding

In a clinical trial, the concealing from the subjects and/or investigators of the identity of the persons receiving the interventions being studied and the control interventions (or standard care). Note: This method is intended to eliminate the possibility that knowledge of which intervention is being received will affect patient outcomes or investigator behaviours that may affect outcomes. Blinding is not always practical (e.g. when comparing surgery to drug treatment), but it should be used whenever it is possible and compatible with optimal patient care.

******

cegamento triplo

Um ensaio no qual os indivíduos, os investigadores (assessores de desfecho) e os estatísticos realizando a análise dos desfechos não sabem quem está em cada grupo sendo comparado. (Conceitos relacionados: cegamento, cegamento único e cegamento duplo). Nota: os termos segamento e mascaramento são sinônimos e o termo mascaramento duplo é preferido sobre o cegamento duplo em ensaios oftalmológicos.

triple-blind

A trial in which the subjects, the investigators (outcome assessors) and the statistician doing the outcomes analysis do not know who is in which comparison group. (Related concepts: blinding, single-blind and double-blind). Note: The terms blinding and masking are synonymous and the term double-masked is preferred over double-blind for ophthalmology trials.

******

cegamento único

Um ensaio onde apenas os investigadores ou os indivíduos sabiam qual intervenção ou tratamento seria ministrado. (Conceitos relacionados: cegamento, cegamento duplo e cegamento triplo). Nota: os termos cegamento e mascaramento são sinônimos e o termo mascaramento duplo é preferido ao invés de cegamento duplo em função de ensaios oftalmológicos.

single-blind

A trial in which only the investigators or subjects know which intervention or treatment is being administered. (Related concepts: blinding, double-blind and triple-blind). Note: The terms blinding and masking are synonymous and the term double-masked is preferred over double-blind for ophthalmology trials.

******

CENTRAL -central de registro de  ensaios controlados da Cochrane

base de dados de ensaios clínicos no campo da saúde, compilado das listas de grupos especializados do "Cochrane Collaboration" (colaboração Cochrane) e de outras organizações e de pesquisas nas bases de dado MEDLINE, EMBASE e outras.

Cochrane central register of controlled trials (CENTRAL)

A database of clinical trials in the health field, compiled from the lists of the specialized groups in the Cochrane Collaboration and other organisations and from searches of MEDLINE, EMBASE and other databases.

******

chance

A proporção (o quociente) da probabilidade de que  um evento ocorrerá com relação à probabilidade de que esse evento não ocorrerá.

odds

The ratio (quotient) of the probability that an event will occur to the probability that this event will not occur. 

******

CINAHL (índice cumulativo de literatura sobre enfermagem e assuntos aliados à saúde)

base de dados eletrônica descrevendo literatura sobre enfermagem e ciências paramédicas publicadas desde 1982.

CINAHL (cumulative index to nursing and allied health literature)

An electronic database describing the nursing and paramedical sciences literature published since 1982.

******

Citação

registro numa base de dados bibliográfica descrevendo documentos tais como artigos, livros e relatórios. Nota: a descrição inclui o(s) nome(s) do(s) autor(es), o título, a fonte, o ano de publicação, e, às vezes, as palavras-chave e resumo.

Citatiton

A record in a bibliographic database describing documents such as articles, books and reports.Note: The description includes the name(s) of the author(s), the title, the source, the year of publication and, sometimes, the keywords and abstract.

******

classificação indevida

A classificação de um indivíduo ou uma característica como sendo de uma categoria diversa daquela para a qual ela foi atribuida, levando a um viés de medida.

misclassification

The classification of a person or a characteristic as being in a category other than that to which it should have been assigned, leading to a measurement bias.

******

CMR - metodologia de registro da Cochrane

banco de dados de estudos metodológicos, publicado pela Biblioteca Cochrane

Cochrane metodology register (CMR)

A database of methodological studies, published by the Cochrane Library.

******

cobertura condicional

financiamento ou restituição (de valores monetários) em tecnologia da saúde ou num serviço condicionado a um critério específico. Nota 1: o financiamento é frequentemente proporcionado por uma agência de cuidado da saúde ou por um pagador, tal como: o governo, organização de manutenção da saúde ou organização de seguro-saúde. Nota 2: os critérios podem ser: - impostos pelo pagador (por exemplo, uma restrição na população elegível para a tecnologia, um acordo de preço/volume ou um finaciamento atrelado ao atingimento de um  desfecho clínico) ou - acordado entre o pagador e o provedor da tecnologia como medida intermediária durante o desenvolvimento da evidência (por exemplo, entrada gerenciada ou cobertura com evidência de arranjos de desenvolvimento)

conditional coverage

The funding or reimbursement of a health technology or service that is conditional on specific criteria. Note 1: The funding is often provided by a health care agency or payer, such as: the government, health maintenance organization or health insurance organization. Note 2: The criteria could be: 
- imposed by the payer (for example, a restriction on the population eligible for the technology, a price-volume agreement or funding tied to the achievement of clinical outcomes), or 
- agreed between the payer and the technology provider as an interim measure during evidence development (for example, managed entry or coverage with evidence development arrangements).

******

coeficiente de correlação

Um número entre -1 e +1 que expressa a força da associação linear entre duas variáveis numéricas. Nota: Numa amostra, a estimativa é representada por r. O coeficiente de correlação igual a zero indica que não há relação linear etre as duas variáveis. Um coeficiente de correlação igual a +1 indica que existe uma relação linear perfeita, e um coeficiente de correlação igual a -1 idica que existe uma relação linear perfeitamente negativa. Nota: Não se pode concluir pela correlação de que existe uma relação de causa e efeito.

correlation coeficiente

A number between -1 and +1 that expresses the strength of the linear association between two numerical variables. Note: In a sample, the estimate is noted as r. A correlation coefficient of 0 indicates that there is no linear relationship between the two variables. A correlation coefficient of +1 indicates that there is a perfect positive linear relationship, and a correlation coefficient of -1 indicates that there is a perfect negative linear relationship. Note: It cannot be concluded from the correlation that there is a cause-and-effect relationship.

******

co-intervenção

num ensaio clínico controlado e randomizado, a aplicação de diagnóstico adicional ou procedimentos terapêuticos aos elementos de um grupo experimental ou ao grupo de controle, ou a ambos.

cointervention

In a randomized controlled trial, the application of additional diagnostic or therapeutic procedures to the members of the experimental group or the control group, or both.

******

co-morbidade

é a presença de doenças coexistentes com a doença sendo estudada

comorbidity

The presence of diseases co-existing with the disease being studied.

******

comparação

processo de gerenciamento da qualidade que uma organização utiliza para estabelecer metas e medir sua performance com relação a organizações reconhecidas por sua excelência.

benchmarking

A quality management process that an organization uses to set goals and measure its performance against that of organizations recognized for their excellence.

******

comparador

em pesquisa clínica, é uma tecnologia ou intervenção que serve com referência em estudos comparativos. Na economia em saúde, é uma opção com a qual a tecnologia ou intervenção é comparada.

comparator

In clinical research, a technology or intervention that serves as a reference in comparative studies. In health economics, an option with which the technology or intervention evaluated is compared.

******

confiabilidade

1) A habilidade de um exame ou teste, feito repetidamente na mesma população, em produzir o mesmo resultado (confiabilidade no teste-reteste). 2) A habilidade de um único exame ou teste em sempre fazer a mesma distinção entre os indivíduos de uma dada população.

reliability

1) The ability of an examination or test, done repeatedly and in the same population, to produce the same result (test-retest reliability). 2) The ability of a single examination or test to always make the same distinction among individuals in a given population.

******

confiabilidade entre avaliadores distintos (confiabilidade inter-avaliadores)

O grau de estabilidade de uma medida quando é repetida sob condições idênticas por avaliadores distintos. Nota: confiabilidade entre avaliadores distintos torna possível determinar o grau ao qual os resultados obtidos podem ser replicados. A falta dessa confiabilidade pode acontecer por divergências entre avaliadores ou pela instabilidade do atributo sendo medido. Conceito relacionado: confiabilidade no mesmo avaliador  (confiabilidade intra-avaliador).

inter-rater reliability

The degree of stability of a measurement when it is repeated under identical conditions by different raters.Note: Inter-rater reliability makes it possible to determine the degree to which the results obtained can be replicated. Lack of this reliability may arise from divergences between raters or instability of the attribute measured. Related concept: intra-rater reliability 

******

confiabilidade entre o mesmo avaliador

O grau de estabilidade observado quando uma medida é repetida sob condições idênticas pelo mesmo avaliador. Nota: a confiabillidade entre o mesmo avaliador torna possível determinar o grau ao qual os resultados obtidos por um procedimento de medição pode ser replicado. A falta de confiabilidade intra-avaliador pode conduzir a divergências entre instrumentos de medida ou a instabilidade do atributo sendo medido. Conceito relacionado: confiabilidade enter-avaliadores.

intra-rater reliability

The degree of stability observed when a measurement is repeated under identical conditions by the same rater. Note: Intra-rater reliability makes it possible to determine the degree to which the results obtained by a measurement procedure can be replicated. Lack of intra-rater reliability may arise from divergences between measurement instruments or instability of the attribute measured. Related concept: inter-rater reliability 

******

confidencialidade

promessa de um profissional ao seu cliente em não revelar informações sem o consentimento do cliente. Outra definição: um requisito ético e regra baseada em privacidade que implica na obrigação dos profissionais da saúde em manter para si o que aprenderam, viram e ouviram na prática de sua profissão. Nota: a confidencialidade é vital para manter o sucesso de uma relação terapêutica. Pela lei, a confidencialidade é considerada explícita ou implícita no contrato entre o paciente e o profissional do qual se requer manter a confidencialidade.

confidentiality

A professional’s promise to his or her client not to reveal information without the client’s consent. Other definition: An ethical requirement and rule based on privacy that implies an obligation for health professionals to keep to themselves what they have learned, seen and heard in the practising of their profession. Note: Confidentiality is vital for maintaining a successful therapeutic relationship. In law, confidentiality is considered an explicit or implicit contract between the patient and the professional that requires the latter to maintain confidentiality.

******

conflito de escolha de tempo

Um método para determinar a preferência entre dois estados de saúde em diferentes durações de tempo, para estimar quantos anos de vida uma pessoa está preparada para sacrificar para melhorar seu estado de saúde. Nota: para estados crônicos, as opções são  a referência do estado de saúde no tempo t seguida pela morte, ou a saúde perfeita por um curto período de tempo seguida pela morte. Para estados temporários, as opções dão a referência do estado de saúde no tempo t seguida por um desfecho específico (usualmente a morte), ou um pior estado de saúde por um curto período de tempo seguida pelo mesmo desfecho.

time trade-off (TTO)

A method for determining preference between two health states for different lengths of time, to estimate how many years of life a person is prepared to sacrifice to improve his/her health status. Note: For chronic states, the options are the reference health state for time t followed by death, or perfect health for a shorter time followed by death. For temporary states, the options are the reference health state for time t followed by an explicitly specified outcome (usually health), or a worse health state for a shorter time followed by the same outcome.

******

conflito de interesse

situação na qual o interesse privado de uma pessoa contribui para o exercício de sua influência sobre a qualidade ou sobre os resultados da precisão na avaliação dos dados.

conflict of interest

A situation in which the private interests of a person contributing to an assessment influence the quality or the results of the assessment or the accuracy of the data.

******

confundidor

fator que distorce o efeito aparente de uma intervenção num desfecho de interesse, ou que distorce a aparente associação entre a exposição e o desfecho. Exemplo: se as pessoas do grupo experimental de um ensaio controlado são mais novas do que as do grupo controle, será difícil decidir se um menor risco de morte num grupo é devido á intervenção ou á diferença de idades. A idade é então denominada confundidor. Nota 1: A identificação de confundidores requer conhecimento especializado ou substantivo sobre a rede causal que formam a intervenção (ou exposição) e o desfecho (por exemplo, conhecimento patopsicológico e conhecimento clínico). Tentativas de se selecionar confundidores somente com base nas associações estatísticas observadas podem conduzor a viéses. Nota 2: Variável confundidora e fator confundidor são sinônimos. Nota 3: termos relacionados incluem viés de confusão.

confounder

A factor that distorts the apparent effect of an intervention on the outcome of interest, or that distorts the apparent association between the exposure and the outcome. Example: If people in the experimental group of a controlled trial are younger than those in the control group, it will be difficult to decide whether a lower risk of death in one group is due to the intervention or to the difference in ages. Age is then said to be a confounder. Note 1: The identification of confounders requires expert or substantive knowledge about the causal network of which the intervention (or exposure) and the outcome are part (e.g. pathophysiological and clinical knowledge). Attempts to select confounders solely on the basis of observed statistical associations may lead to bias. Note 2: Synonyms include confounding variable and confounding factor. Note 3: Related terms include confounding bias.

******

consentimento informado

A obrigação ética e legal em não realizar algum procedimento médico significativo até que o competente paciente tenha sido informado da natureza e riscos do procedimento e as alternativas ao mesmo, bem como o prognóstico se o procedimento não for realizado. Nota: se o paciente concordar com o procedimento, ele ou ela devem fazê-lo com liberdade e voluntariamente.

informed consent

The legal and ethical obligation not to perform any significant medical procedure until a competent patient has been informed of the nature and risks of the procedure and the alternatives to it, as well as of the prognosis if the procedure is not done. Note: If the patient agrees to the procedure, he or she must do so freely and voluntarily.

******

consequência

Desfecho positivo ou negativo de uma doença ou intervenção, expressa qualitativa ou quantitativamente. Nota: por exemplo, acidente vascular cerebral, morte, efeitos colaterais ou doença evitada

consensus report

The positive or negative outcome of a disease or intervention, expressed qualitatively or quantitatively. Note: For example, stroke, death, side effects or avoided disease.

******

construtivismo social

Uma doutrina filosófica em ciência e conhecimento que postula não haver objetivo ou realidade absolutamente social, mas apenas várias formas de interpretação dessa relaidade. Sinônimo: construcionismo social.

social constructivism

A philosophical doctrine on science and knowledge that postulates that there is no objective or absolute social reality, but only various ways of interpreting that reality. Syn.: social constructionism

******

consumidor

Pessoa  que usa, é afetada, intitulada ou compelida a usar um serviço de saúde. Nota: no campo da saúde, o termo consumidor é usado principalmente nos Estados Unidos, onde não existe um sistema de saúde universal. Em outros países, o termo paciente é frequentemente utilizado, mas como essa palavra deveria ser aplicada somente a pessoas que consultam um médico, termos como usuário, recipiente e cliente são utilizados no sistema de saúde canadense.

consumer

A person who uses, is affected by, is entitled to or is compelled to use a health service. Note: In the health care field, the term consumer is used mainly in the United States, where there is no universal health insurance system. Elsewhere, patient is often used, but since this word should be applied only to persons who consult a physician, terms such as user, recipient and client are used in the Canadian health system.

******

contaminação

Em ensaios clínicos, a situação que ocorre quando membros do grupo de controle recebem a intervenção experimental ou quando os elementos do grupo de intervenção não a recebem.

contamination

In clinical trials, the situation that occurs when the members of the control group receive the experimental intervention or when the subjects in the experimental group do not receive the intervention.

******

conteúdo atual

Base de dados eletrônica que provê acesso a tabelas de conteúdo e dados bibliográficos de publicações recentes dos principais jornais científicos e dos principais livros  em ciências, ciências sociais, artes e humanidades.

current contents

An electronic database that provides access to the tables of contents and bibliographic data from recent issues of the major science journals and the leading books in the sciences, social sciences, arts and humanities.

******

contexto

Condições e circunstâncias nas quais a intervenção é aplicada. Nota: por exemplo, a preparação do ambiente (no hospital, em casa ou numa ambulância aérea), o tempo (dia útil, feriado, período noturno), o tipo de prática (cuidados primários, secundários ou terciários, prática de seguro, caridade).

context

The conditions and circumstances in which an intervention is applied. Note: For example, the setting (in hospital, at home, in an air ambulance), the time (working day, holiday, night time), the type of practice, (primary, secondary or tertiary care, private practice, insurance practice, charity).

******

contra-indicação

Qualquer circunstância indicando que a intervenção poderia ser inadequada

contraindication

Any circumstance indicating that an intervention would be inappropriate.

******

controle

1. Em ensaios clínicos, ao se comparar duas ou mais intervenções um elemento do grupo de controle ao qual é oferecido um placebo,  não recebe tratamento ou recebe o cuidado padrão. 2. Em estudos de caso-controle, uma pessoa do grupo de comparação que não tem a doença ou o estado clínico de interesse. 3. Em controle estatístico, um procedimento que ajusta os resultados para levar em consideração fatores estranhos que poderiam distorcê-los. 4. Controle de infecção. Em saúde pública, um programa que deseja reduzir a extensão ou as consequências de uma doença infecciosa.

control

1. In clinical trials comparing two or more interventions, a subject in the comparison group who is offered a placebo, receives no treatment or receives standard care. 2. In case-control studies, a person in the comparison group who is without the disease or clinical state of interest. 3. statistical control. In statistics control, a procedure to adjust the results to take into account extraneous factors that could distort them. 4. infection control 
In public health, a programme aimed at reducing the extent or the consequences of an infectious disease.

******

controle concorrente

um grupo de controle que é observado pelos investigadores ao mesmo tempo do grupo de intervenção, onde os dois grupos não foram definidos por randomização. Nota: podem ocorrer diferenças nas características dos elementos dos dois grupos.

concurrent control

A control group that is observed by the investigators at the same time as the treatment group, where the two groups were not established using randomisation. Note: Differences in the characteristics of the subjects in the two groups may result.

******

controle histórico

Um grupo de controle composto de pessoas que foram observadas numa ocasião anterior à presente, envolvendo a observação do grupo de interesse. Nota: a validade das comparações com esse tipo de grupo de controle é suspeita, porque o grupo histórico tende a diferir do grupo atual em sua composição, diagnóstico, severidade da doença, medidas dos desfechos, ou outros meios importantes que poderiam influenciar as descobertas da pesquisa. Pode ser factível usar controles históricos em circunstâncias especiais onde os desfechos de um tratamento padrão (ou a ausência de tratamento) forem bem conhecidos e variem pouco para uma dada população.

historical control

A control group made up of persons who have been observed on an occasion previous to the present one involving observation of the group of interest. Note: The validity of comparisons with this type of control group is suspect because the historical group is likely to differ from the current group in its composition, diagnosis, disease severity, measurement of outcomes, or other important ways that could influence the research findings. It may be feasible to use historical controls in special instances where the outcomes of a standard treatment (or no treatment) are well known and vary little for a given population. 

******

cuidador

1) pessoa devidamente treinada e paga que fornece cuidados a uma pessoa com uma doença ou com uma incapacidade. 2) pessoa (frequentemente familiar ou amigo),  remunerado ou não, que fornece cuidado de algum tipo,  regularmente a uma pessoa com uma doença ou incapacidade

carer

1) A duly trained and paid person who provides a person with a disease or disability with care. 2) A person (often a family member or friend), paid or unpaid, who regularly provides a person with a disease or disability with any form of care.

******

cuidados com a saúde baseados em evidências

Os cuidados e serviços resultantes da aplicação de princípios de medicina baseada em evidências para todas as profissões associadas com cuidados à saúde, incluindo o gerenciamento e as compras de bens e serviços.

evidence-based health care

The care and services flowing from the application of the principles of evidence-based medicine to all professions associated with health care, including management and the purchasing of goods and services.

******

curva ROC - característica de operação do receptor

veja curva ROC

receiver operating characteristic (ROC) curve

See ROC curve.

******

curva ROC (Característica de Operação do Receptor)

Na avaliação de um diagnóstico ou de um teste de triagem, uma representação gráfica da relação entre a proporção de verdadeiros  positivos (sensitividade) e a proporção de falsos positivos (1-especificidade) para vários pontos positivos de corte do teste. Nota: a área sob a curva ROC é uma expressão da performance do teste independentemente da população paciente e pode ser utilizada par comparar vários testes.

ROC (Receiver Operating Characteristic) curve

In the evaluation of a diagnostic or screening test, a graphical depiction of the relationship between the true positive ratio (sensitivity) and the false positive ratio (1 - specificity) for various positivity cut-off points of the test. Note: The area under the ROC curve is an expression of a test’s performance independent of the patient population and can be used to compare several tests.

******

custo

Produto da quantidade de um recurso pelo preço unitário deste.

cost

The product of the quantity of a resource and the unit price of that resource.

******

custo de aquisição

Preço pago por uma instituição, agência ou pessoa na compra de uma droga, produto ou serviço de saúde.

acquisition cost

The price paid by an institution, agency or person for the purchase of a drug, device, product or health service.

******

custo de oportunidade

O valor dos benefícios de uma melhor opção que é oferecida quando outra opção é escolhida

opportunity cost

The value of the benefits of a better option that is given up when another option is chosen.

******

custo direto

Todos os custos fixos ou variáveis dos recursos (bens, serviços, et.) monopolizados na implementação de uma intervenção e gerenciando suas consequências. Nota: Drummond e seus colaboradores não suportam o uso deste conceito.

direct cost

All the fixed or variable costs of the resources (goods, services, etc.) monopolized in implementing an intervention and managing its consequences. Note: Drummond and his collaborators do not support the use of this concept.

******

custo direto não-médico

Todas as despesas não-médicas associadas à entrega de cuidados com a saúde e com serviços de saúde. Nota: por exemplo, despesas com o cuidado de crianças e despesas realcionadas a transporte para o recebimento de cuidados. Nota: Drummond e seus colaboradores não suportam o uso deste conceito.

direct non-medical cost

All non-medical expenses associated with the delivery of health care and health services. Note: For example, childcare expenses and expenses connected with travel to receive care. Note: Drummond and his collaborators do not support the use of this concept.

******

custo do capital

custo de um item que permanece útil além do período de aquisição. Nota: custos de capital incluem a depreciação da propriedade utilizada pelo item (infraestrutura física e equipamentos, por exemplo), bem como os ativos não depreciáveis, como o terreno.

capital cost

The cost of an item that remains useful beyond the acquisition period. Note: Capital costs include depreciable property, such as tangible capital assets (physical infrastructure and equipment, for example), as well as non-depreciable assets, such as land.

******

custo do tempo perdido

Custo das horas perdidas num trabalho ou a diminuição da produtividade devido a uma doença, incapacidade ou morte. Nota: o valor do tempo é geralmente calculado com base na média da renda.

cost of lost time

The cost of lost hours of work and decreased productivity due to disease, disability or death. Note: The value of the time is generally calculated on the basis of the average earnings.

******

custo futuro de cuidado com a saúde

Todos os custos resultantes do consumo de recursos adicionais após uma dada intervenção (porque isso aumenta a expectativa de vida, por exemplo).

future health care cost

All costs resulting from the consumption of additional resources following a given intervention (because it increases life expectancy, for example).

******

custo incremental

A diferença entre o custo da adoção de uma opção e o custo da adoção de outra opção, com a qual estiver sendo comparada.

incremental cost

The difference between the cost of an option and the cost of another option with which it is compared.

******

custo indireto

Todos os custos atribuidos ao valor de uma produção econômica perdida, devido a uma doença, injuria incapacitante.

indirect cost

All costs attributed to the value of economic production lost due to disease, a disabling injury or premature death.* •Not to be confused with indirect costs in accounting, where the term refers to overhead costs. Note: Drummond and his collaborators do not support the use of this concept.

******

custo intangível

O custo não quantificável da dor e sofrimento causados por uma doença, problema de de saúde ou intervenção. Nota: Drummond e seus colaboradores não endossam o uso deste conceito.

intangible cost

The non-quantifiable cost of pain and suffering caused by a disease, health problem or intervention. Note: Drummond and his collaborators do not support the use of this concept. 

******

custo marginal

O custo adicional requerido para produzir uma unidade adicional de benefício. Nota: por exemplo, o custo adicional requerido para produzir uma unidade adicional de desfecho em saúde.

marginal cost

The additional cost required to produce an additional unit of benefit. Note: For example, the additional cost required to produce an additional unit of health outcome.

******

custo médico direto

Todos os custos fixos diretamente relacionados à entrega de cuidados com a saúde e com serviços de saúde. Nota: por exemplo, a compensação (remuneração) do médico, taxas hospitalares e medicamentos.  Nota: Drummond e seus colaboradores não suportam o uso deste conceito.

direct medical cost

All the fixed or variable costs directly related to the delivery of health care and health services. Note: For example, physicians’ compensation, hospital fees and drugs. Note: Drummond and his collaborators do not support the use of this concept.

******

custo médio

custo total de um tratamento ou programa dividido pelo número total de unidades de tratamento proporcionadas

average cost

The total cost of a treatment or programme, divided by the total number of treatment units provided.

******

custo não relacionado

Os custos não especificamente atribuidos a um caminho terapêutico e suas consequências.

unrelated cost

The costs not specifically attributable to a therapeutic pathway and its consequences.

******

custo por QALY

Medida utilizada na análise de custo-utilidade para comparar programas, intervenções ou tratamentos, expressos como um custo unitário por unidade de desfecho (efetividade), ajustada com base na qualidade de vida.

cost per QALY

A measure used in cost-utility analysis to compare programmes, interventions or treatments, expressed as a monetary cost per unit of outcome (effectiveness), adjusted on the basis of quality of life.

******

custo recorrente

Todos os custos que ocorrem periodicamente - anualmente, por exemplo.

recurrent cost

All costs that occur periodically—each year, for example.
