# J {-}

Justiça

O princípio de equidade que estabelece que as pessoas devem ser tratadas igualmente. Outra definição: a retidão no entendimento, reconhecimento e respeito aos direitos de cada pessoa e o requerimento de dar a cada um aquilo que a mesma está intitulada, de acordo com as adequadas regras de alocação. Justiça distributiva: o princípio de justiça aplicado à distribuição de bens comuns que estabelece o compartilhamento proporcional e um adequado uso dos recursos. (Conceito relacionado: equidade.)

Justice

The principle of fairness that states that people must be treated equally. Other definition: A rectitude in understanding, recognising and respecting the rights and merit of each person and a requirement to give to each that to which he or she is entitled, in accordance with appropriate allocation rules. Distributive justice: The principle of justice applied to the distribution of common goods that establishes a proportional sharing and an appropriate use of resources. (Related concept: equity).

