# Q {-}

qualidade metodológica

A medida em que o projeto, a conduta e a análise de um estudo provavelmente terão impedido um erro sistemático e ter produzido resultados confiáveis e válidos. Nota 1: Estudos de melhor qualidade são mais propensos a produzir resultados que são menos tendenciosos e mais próximos do valor verdadeiro para um resultado do que estudos de qualidade mais fraca.

methodological quality

The extent to which the design, conduct and analysis of a study are likely to have preventedsystematic error and to have produced results that are reliable and valid. Note 1: Better quality studies are more likely to yield results that are less biased and closer to the true value for an outcome than poorer quality studies.

******

qualidade

Todas as características de um bem ou serviço que vem de encontro às necessidades e expectativas do usuário, continuamente. Nota: qualidade pode ser definida usando-se diversos critérios: confiabilidade, disponibilidade, sustentabilidade, segurança no uso, custo do uso, etc. Qualidade é medida usando-se indicadores de estrutura, processo e desfecho.

quality

All the characteristics of a good or service that enable it to meet users’ needs and expectations on an ongoing basis. Note: Quality can be defined using several criteria: reliability, availability, sustainability, operating safety, cost of use, etc. Quality is measured using structure, process and outcome indicators.

******

qualidade da evidência

O grau para o qual o projeto de pesquisa e a condução do estudo nos quais a evidência está baseada, tem feito isso possível para se obter resultados válidos.

quality of evidence

The degree to which the research design and the conducting of the study on which the evidence is based have made it possible to obtain valid results.

******

qualidade de vida

veja qualidade de vida relacionada à saúde.

quality of life (QOL)
See health-related quality of life.

******

qualidade de vida relacionada à saúde

As medidas do impacto de uma intervenção no estado de saúde de pacientes, indo além das tradicionais medidas de mortalidade e morbidade para incluir dimensões tais como: fisiologia, função, vida social, cognição, emoções, dormir e descansar, energia e vitalidade, percepção de saúde e satisfação com a vida em geral. Nota: alguns desses elementos são também chamados de estado da saúde, estado funcional ou medidas de qualidade de vida.

health-related quality of life (HRQL,HRQoL,QOL)

The measures of the impact of an intervention on patients’ health status, extending beyond the traditional measures of mortality and morbidity to include dimensions such as physiology, function, social life, cognition, emotions, sleep and rest, energy and vitality, health perception and general life satisfaction. Note: Some of these elements are also called health status, functional status or quality-of-life measures.

******

qualidade do cuidado

O grau para o qual o cuidado com a saúde aumenta a probabilidade de se obter o desfecho desejado e atender os padrões de cuidados. (Conceitos relacionados: avaliação da qualidade e garantia da qualidade).

quality of care

The degree to which health care increases the probability of achieving the desired health outcomes and meets the standards of care. (Related concepts: quality assessment and quality assurance).
