# P {-}

paciente

Uma pessoa, apresentando sinais clínicos ou não, que consulta um médico. Veja consumidor.

patient

A person, presenting with clinical signs or not, who consults a physician. See consumer.

******

padrão do melhor interesse

O princípio da beneficência em que deve basear-se em qualquer decisão relativa a um paciente que não consegue expressar seus desejos.

best interest standard

The beneficence principle on which must be based any decision relating to a patient who is unable to express his or her wishes.

******

padrão-ouro

O método, procedimento ou medida que é largamente aceita como sendo a melhor, e contra a qual novos procedimentos devem ser comparados. Nota: é particularmente importante usar um padrão-ouro em estudos de acurácia de testes diagnósticos.

gold standard

The method, procedure or measurement that is widely accepted as being the best and that against which new ones should be compared. Note: It is particularly important to use such a gold standard in studies of the accuracy of diagnostic tests.

******

perspectiva analítica

o ponto de vista escolhido para uma dada análise, incluindo o ponto de vista da sociedade, do governo, do sistema de saúde ou do contribuinte.

analytic perspective

The viewpoint chosen for a given analysis, including a viewpoint of society, the government, the health care system or the payer.

******

pesquisa com ação participativa

veja pesquisa de ação

participatory action research

See action research

******

pesquisa de serviços de saúde

Um campo interdisciplinar de pesquisa que examina o impacto: da organização, do financiamento e da gestão de serviços de cuidados com a saúde administrando: entrega, qualidade, custo, acessibilidade e desfechos de tais serviços.

health services research

An interdisciplinary field of inquiry that examines the impact of the organization, financing and management of health care services on the delivery, quality, cost, accessibility and outcomes of such services.

******

pesquisa manual

A busca metodológica manual, página a página, do conteúdo de um jornal, incluindo artigos, editoriais, cartas dos leitores, por exemplo, com a finalidade de identificar estudos relevantes e completar as buscas não indexadas à base de dados. Nota: normalmente, se começa à partir do ano corrente e então se retrocede no tempo, até a produção se tornar desprezível ou até se encontrar o primeiro volume.

handsearching

The methodological searching, page by page (by hand) of the content of a journal, including articles, editorials, letters from readers, etc., to identify the relevant studies and complete the non-indexed searching in the databases. Note: Normally, one starts with the issues from the current year, and then works backwards until the yield becomes negligible or the first volume is reached.

******

pesquisa primária

Investigação na qual os dados são coletados pela primeira vez diretamente dos pacientes (ensaio randomizado controlado, estudo observacional, séries de casos, etc.) Nota: O termo "pesquisa primária" é frequentemente utilizado para distinguir esse tipo de pesquisa da "pesquisa secundária", que é uma pesquisa sintética (re-análise de dados previamente coletados), meta-análise e outros tipos de estudos combinados (tais como análises econômicas e análises de decisão). Conceito realacionado: pesquisa secundária. Sinônimos: estudo primário, estudo original.

primary research

An investigation in which the data are collected for the first time directly from patients (randomized controlled trial, observational study, case series, etc.). Note: The term “primary research” is often used to distinguish this type of research from “secondary research,” which is synthesis research (re-analysis of previously collected data), meta-analyses and other ways of combining studies (such as economic analysis and decision analysis). Related concept: secondary research. Syn.: primary study, original study.

******

pesquisa secundária

Um tipo de pesquisa que não produz dados originais, mas envolve a síntese qualitativa ou quantitativa de informação a partir de múltiplos estudos originais. Nota: revisões de literatura, meta análises, análises de decisão e relatórios de consenso são exemplos de pesquisa sintética. Sinônimo:  estudo sintético.

secondary research

A type of research that does not produce original data, but that involves the qualitative or quantitative synthesis of information from multiple original studies. Note: Literature reviews, meta-analyses, decision analyses and consensus reports are examples of synthesis research. Syn. : synthetic study.

******

placebo

Num cenário clínico,  um tratamento ou intervenção que é inativo, mas que pode agir através de um mecanismo psicológico (efeito placebo) se o paciente acredita estar recebendo um tratamento ou uma intervenção ativos. Em pesquisa, um tratamento fictício dado a um grupo controle, impossível de ser diferenciado do tratamento real dado ao grupo de tratamento, usado para isolar o efeito do tratamento sendo estudado.

placebo

The effect on a patient’s health status (improvement or worsening) that may occur due to the patient’s expectation that a particular intervention will have an effect.

******

poder

Em teste de hipóteses, a probabilidade de rejeição de uma falsa hipótese nula, isto é, concluindo que um tratamento é efetivo quando o efeito do tratamento de uma dada magnitude realmente existe, por exemplo. Nota: na presença de uma verdadeiramente falsa hipótese nula (quando há um efeito verdadeiro do tratamento, de uma dada magnitude, por exemplo), o poder é a probabilidade de se evitar um erro do Tipo II, e assim corresponde a (1 - β).

power

In hypothesis testing, the probability of rejecting a false null hypothesis, i.e. of concluding that a treatment is effective when a treatment effect of a given magnitude truly exists, for example. Note: In the presence of a truly false null hypothesis (when there is a true treatment effect of a given magnitude, for example), the power is the probability of avoiding a Type II error and therefore corresponds to (1 - β).

******

poder da evidência

A significância clínica e estatística dos resultados de um estudo, determinados pela magnitude, precisão e reprodutibilidade do efeito da intervenção sendo estudada. Nota: em estudos não randomizados, fatores adicionais tais como a plausibilidade biológica, gradente biológico e consistência longitudinal de associações, podem ser considerados.

strength of evidence

The clinical and statistical significance of the results of a study, determined by the magnitude, precision and reproducibility of the effect of the intervention being studied. Note: In nonrandomised studies, additional factors, such as biological plausibility, biological gradient and longitudinal consistency of associations, may be considered.

******

poder estatístico

Veja poder.


Statistical power

See power.

******

ponto final

Um indicador escolhido para determinar o efeito de uma intervenção.

endpoint

An indicator chosen for determining the effect of an intervention.

******

prática inadequada

Uma avaliação subjetiva do tamanho do efeito estimado na parametrização de um ensaio clínico.

malpractice

A subjective evaluation of the size of the estimated effect in a clinical setting.

******

precisão

1) A qualidade de uma estimativa pontual obtida de um conjunto de observações tendo uma variância pequena. Nota: um intervalo de confiança estreito ao redor de um ponto estimado indica uma estimativa mais precisa do efeito, do que um intervalo de confiança largo. Note que uma estimativa precisa não é necessariamente acurada. 2) Uma medida de verossimilhança de erros randômicos nos resultados de um estudo, meta análise ou medida. Nota: em meta análise, o peso dado aos resultados de cada estudo sobre a estimativa geral do efeito de uma intervenção é frequentemente baseado na precisão de cada estudo, a qual é estimada usando-se o inverso da variância da estimativa do efeito do tamanho da amostra. 3) em pesquisa de literatura, o número de citações relevantes dividido pelo número total de citações coletadas, isto é, a proporção de estudos atendendo o critério de inclusão em registros de ensaios clínicos ou numa revisão literária. (termo relacionado: acurácia).

precision

1)	A quality of a point estimate obtained from a set of observations having a small variance. Note: A narrow confidence interval around a point estimate indicates a more precise estimate of effect than a wide confidence interval. Note that a precise estimate is not necessarily accurate. 2) A measure of the likelihood of random errors in the results of a study, meta-analysis or measurement. Note: In a meta-analysis, the weight given to the results of each study in the overall estimate of the effect of an intervention is often based on the precision of each study, which is estimated using the inverse of the variance of the estimate of effect or the sample size. 3) In a literature search, the number of relevant citations, divided by the total number of citations retrieved, i.e. the proportion of studies meeting the inclusion criteria for a clinical trials register or a literature review. (Related concept: accuracy)

******

preferência

No contexto da saúde, o quão desejável é um desfecho clínico. Nota: utilidade e valor são aplicações específicas deste conceito.

preference

In the context of health, the desirability of a clinical outcome. Note: Utility and value are specific applications of this concept.

******

preferência revelada

Uma preferência deduzida das escolhas que um indivíduo faz. Nota: preferências podem ser reveladas por escolhas feitas na definição natural ou nas respostas às questões de um investigador.

revealed preference

A preference deduced from the choices that an individual makes. Note: Preferences may be revealed by choices made in a natural setting or by responses to an investigator’s questions.


******

prevalência

O número de pessoas de uma população com uma doença ou condição, num dado momento, usualmente expressa como a proporção do número de pessoas afetadas pelo total da população.

prevalence

The number of people in a population with a specific disease or condition at a given time, usually expressed as a proportion of the number of affected people to the total population.

******

previsão clínica

ferramenta para assistir a decisão clínica, podendo ser usada para determinar a probabilidade de resposta ao tratamento ou para propor um diagnóstico ou o curso de uma ação terapêutica, baseada nas váriáveis obtidas do histórico do paciente, exames físicos ou resultados de testes.

clinical prediction

A tool for assisting clinical decision making that can be used to determine the probability of response to a treatment or to propose a diagnostic or therapeutic course of action on the basis of variables obtained from the patient’s history, physical exam or test results.

******

probabilidade de transição

A probabilidade de que a saúde de um paciente se altere de um estado a outro dentro de um dado período.

transition probability

The probability that the health of a patient changes from one state to another within a given period.

problemas de alvo móvel

Mudanças nos cuidados de saúde que podem tornar as avaliações da tecnologia da saúde desatualizadas, às vezes mesmo antes que as recomendações que delas saem possam ser implementadas. Nota: São incluídas mudanças na tecnologia mãe, em uma de suas variantes ou em uma tecnologia complementar (usada para tratar um determinado problema de saúde), emergência de novas tecnologias concorrentes e mudanças na aplicação de uma tecnologia (por exemplo, para diferentes populações de pacientes ou a diferentes problemas de saúde). Ortografia alternativa: problema de destino móvel

******

moving target problem

Changes in health care that can render health technology assessments out-of-date, sometimes even before the recommendations that come out of them can be implemented. Note: Included are changes in the mother technology, in one of its variants or in a complementary technology (used to treat a given health problem), emergence of new competing technologies, and changes in the application of a technology (e.g. to different patient populations or to different health problems). Alternative spelling: moving-target problem

******

processo de julgamento

Um processo no qual um documento é enviado a editores e revisores  experientes, especialistas no tema do documento,  a especialistas em metodologia ou a usuários. 

referee process

A process whereby a document is sent to expert editors and reviewers who are specialists in the field, methodological specialists or users.

******

prognose

Uma avaliação do curso futuro do desfecho de uma doença.

prognose

An assessment of the future course and outcome of a disease.

******

projeto de cruzamento

Projeto de pesquisa no qual os elementos recebem, em sequência, a intervenção experimental (ou a intervenção de controle) e então, após um tempo especificado, (fase sem intervenção), a intervenção de controle (ou a intervenção experimental). Nota: neste projeto, cada elemento atua no controle de si mesmo(a), e a randomização pode ser usada para determinar a ordem na qual o elemento recebe a intervenção experimental e a intervenção de controle.

crossover design

A research design in which the subjects receive, in sequence, the experimental intervention (or the control intervention), then, after a specified time, (phase without intervention), the control intervention (or the experimental intervention). Note: In this design, each subject serves as his/her own control, and randomisation may be used to determine the order in which a subject receives the experimental intervention and the control intervention.

******

projeto fatorial

Um projeto que permite a avaliação de efeitos de múltiplas intervenções e suas interações dentro de um ensaio clínico. Nota: a maioria dos ensaios consideram apenas uma interveção experimental, comparando-a com uma ou mais opções de placebo. Num ensaio utilizando um projeto fatorial 2x2, os participantes são alocados em uma de quatro possíveis combinações. Por exemplo, num ensaio randomizado controlado de terapia de substituição da nicotina e aconselhamento, os participantes poderiam ser alocados nos seguintes grupos: somente com a  terapia de substituição da nicotina, somente aconselhamento, ambos ou nenhum. Assim, é possível testar o efeito independente de cada intervenção na cessação do fumo e o efeito combinado (da interação entre) as duas intervenções.

factorial design

A design that allows for evaluating the effects of multiple interventions and their interactions within a clinical trial. Note: Most trials consider only one experimental intervention, comparing it with one or more options or a placebo. In a trial using a 2x2 factorial design, participants are allocated to one of four possible combinations. For example, in a randomised controlled trial of a nicotine replacement therapy and counselling, participants would be allocated to: nicotine replacement therapy alone, counselling alone, both, or neither. In this way it is possible to test the independent effect of each intervention on smoking cessation and the combined effect of (interaction between) the two interventions.

******

projeto pareado

Um projeto de pesquisa no qual os indivíduos ou grupos de indivíduos são pareados (com base em fatores de prognóstico, por exemplo) e um membro de cada par é alocado no grupo experimental e o outro no grupo controle.

paired design

A research design in which the subjects or groups of subjects are matched (on the basis of prognostic factors, for example) and one member of each pair is allocated to the experimental group and the other to the control group.

******

proporção de risco

Veja risco relativo.

risk ratio

See relative risk.

******

proporção do custo-efetividade incremental

O custo adicional da intervenção mais dispendiosa comparado com o custo da intervenção menos dispendiosa, dividido pela diferença entre os efeitos das intervenções nos pacientes (o custo adicional por QALY, por exemplo).

incremental cost-effectiveness ratio (ICER)

The additional cost of the more expensive intervention compared with the less expensive intervention, divided by the difference between the effects of the interventions on the patients (the additional cost per QALY, for example).

******

protocolo  

O plano ou conjunto de passos a serem seguidos num estudo. Nota: por exemplo, um protocolo para uma revisão sistemática deve descrever o propósito da revisão, seus objetivos e os métodos a serem usados para localizar, selecionar e avaliar criticamente os estudos incluídos, e para coletar e analisar os dados dos mesmos.

protocol

The plan or set of steps to be followed in a study. Note: For example, a protocol for a systematic review must describe the purpose of the review, its objectives and the methods to be used to locate, select and critically appraise the included studies, and to collect and analyse data from them.

******

protocolo per

Uma análise que exclui indivíduos que não aderiram ao regime da intervenção (fizeram tratamentos concorrentes, por exemplo). Nota: a população de interesse é assim altamente selecionada e não influenciada por fatores que possam diluir o efeito do tratamento. Esta forma de análise pode assim produzir uma maior estimativa do efeito do tratamento. (conceito relacionado: análise da intenção de tratamento). Outra definição: uma análise de um subconjunto de indivíduos de um ensaio randomizado controlado que aderiu ao protocolo suficientemente para ter uma boa probabilidade dos seus desfechos demonstrarem o feito da intervenção de interesse. Este subconjunto pode ser definido com base na exposição à intervenção, à disponibilidade das medidas e à falta de maiores resultados do protocolo. Esta estratégia de análise pode estar sujeita a viéses porque a não aderência ao protocolo pode ser devida à intervenção.

per protocol

An analysis that excludes subjects who were not compliant with the intervention regimen (took prohibited concurrent treatments, for example). Note: The population of interest is thus highly filtered and not influenced by factors that could dilute the effect of treatment. This form of analysis may therefore produce a larger estimate of treatment effect. (Related concept: intention-to-treat analysis). Other definition: An analysis of the subset of subjects of a randomised controlled trial who have complied with the protocol sufficiently for there to be a good chance that their outcomes demonstrate the effect of the intervention of interest. This subset may be defined on the basis of exposure to the intervention, the availability of measurements and the lack of major departures from the protocol. This analysis strategy may be subject to bias because the non-compliance with the protocol may be due to the intervention.

******

pseudo-randomização

Veja randomização e exclusão de alocação. 

pseudorandomization

See randomization and concealment of allocation. Alternate spellings: pseudorandomisation, pseudo-randomisation, pseudo-randomization.

******

PubMed

Um banco de dados da Biblioteca Nacional de Medicina dos Estados Unidos que inclui cerca de 18 milhões de citações à partir do MEDLINE e de outros periódicos de artigos biomédicos publicados desde o início do século vinte. Nota: Pubmed inclui links para sites provendo o texto completo dos artigos. Inclui não somente a base de dados MEDLINE mas também a  base OLDMEDLINE, artigo em processo e registros de artigos fornecidos por editoras. Está disponível, sem custo, na Internet em http://www.ncbi.nlm.nih.gov/sites/entrez?db=pubmed.  

PubMed

An electronic database of medical articles produced by the United States National Library of Medicine.
