# M {-}

magnitude do efeito do tratamento

Uma avaliação subjetiva do tamanho do efeito estimado na parametrização de um ensaio clínico.

magnitude of treatment effect

A subjective evaluation of the size of the estimated effect in a clinical setting.

******

mascaramento

Veja cegamento.

masking

See blinding.

******

média
Uma medida de tendência central calculada pela divisão da soma dos valores observados pelo número de observações. Nota: a palavra média usada isoladamente geralmente se refere à média aritmética. Sinônimo:  média aritmética

mean

A measure of central tendency calculated by dividing the sum of all the observed values by the number of observations. Note: The word mean used alone generally refers to the arithmetic mean. Syn.: arithmetic mean

******

média aritmética

veja média

arithmetic mean

see mean

******

mediana

Uma medida de tendência central correspondente ao valor abaixo do qual 50% são encontradas 50% das observações. Nota: a mediana é o ponto médio das observações classificadas em ordem ascendente. Ela pode proporcionar uma melhor estimativa da média quando valores extremos causam assimetria na distribuição das observações.

median

A measure of central tendency corresponding to the value below which 50% of the observations are found. Note: The median is the midpoint of observations ranked in ascending order. It can provide a better estimate of the mean when extreme values cause asymmetry in the distribution of the observations.

******

medicina baseada em evidências

Um tipo de medicina baseado no uso da melhor evidência proveniente de pesquisa médica e científica na tomada de decisões sobre o cuidado com pacientes individuais. Nota: este enfoque envolve a formulação de uma questão clara e específica baseada num problema específico de saúde, sistematicamente pesquisando-se a literatura científica e médica sobre o problema, determinando-se os indicadores de interesse, apreciando criticamente os resultados relevantes e usando as conclusões resultantes na rotina da prática médica.

evidence-based medicine

A type of medicine based on using the best evidence from scientific and medical research to make decisions about the care of individual patients. Note: This approach involves formulating a clear and specific question based on a specific health problem, systematically searching the scientific and medical literature on the problem, determining the indicators of interest, critically appraising the relevant results and using the resulting conclusions in routine medical practice.

******

MEDLARS (Medical Literature Analysis and Retrieval System) (sistema de arquivamento e análise de Literatura Médica)

Um sistema computadorizado compreendendo cerca de 40 bases de dados médicas gerenciadas pela Biblioteca Nacional de Medicina dos Estados Unidos.

MEDLARS (Medical Literature Analysis and Retrieval System)

A computerized system comprising about 40 medical databases managed by the United States National Library of Medicine.

******

MEDLINE (MEDlars onLINE)

Uma base de dados eletrônica de artigos médicos produzida pela  Biblioteca Nacional de Medicina dos Estados Unidos. Nota: em 2008, haviam indexados acima de 17 milhões de referências de cerca de 5 mil periódicos biomédicos publicados desde 1966. (Conceito relacionado: PubMed)

MEDLINE (MEDlars onLINE)

An electronic database of medical articles produced by the United States National Library of Medicine. Note: In 2008, there were over 17 million references from about 5,000 biomedical journals published since 1966 indexed in it. (Related concept: PubMed)

******

MeSH (Medical Subject Headings) (descritores de referências médicas)

Descritores médicos que comõe o vocabulário controlado de cerca de 19 mil termos usados na MEDLINE e em outras determinadas bases de dados da United States National Library of Medicine (Biblioteca Nacional de Medicina dos Estados Unidos).

Medical Subject Headings (MeSH)

The medical descriptors that are part of a controlled vocabulary of about 19,000 terms used in MEDLINE and certain other United States National Library of Medicine MEDLARS databases.

******

meta-análise  

Um método estatístico que consiste em combinar sistematicamente resultados de diferentes estudos para obter uma estimativa quantitativa do efeito geral de uma determinada intervenção ou variável.

meta-analysis

A statistical method that consists of systematically combining results from different studies to obtain a quantitative estimate of the overall effect of a particular intervention or variable.

******

meta-análise cumulativa

Meta-análise apresentando o acúmulo gradual dos resultados de estudos, à medida em que os estudos são adicionados. Nota: no gráfico de uma meta-análise cumulativa, cada linha horizontal representa a integração dos estudos precedentes, ao invés de apresentar os resultados de um único estudo. Os estudos são integrados um a cada vez, numa ordem especificada (por exemplo, de acordo com a data da publicação ou com a qualidade).

cumulative meta-analysis

A meta-analysis presenting the gradual accumulation of the results of studies as the studies are added. Note: In a cumulative meta-analysis graph, each horizontal line represents the integration of the preceding studies, rather than the results of a single study. The studies are integrated one at a time and in a specified order (e.g. according to the date of publication or quality).

******

meta-regressão

Em uma meta-análise, um modelo de regressão para estudar a relação entre as diferentes características do estudo e a estimação do efeito observado nesses estudos. Nota: As características do estudo são, por exemplo, o método de distribuição nos grupos, o tipo de cegamento, o risco inicial e o cronograma de administração de intervenção.

meta-regression

In a meta-analysis, a regression model for studying the relationship between the different study characteristics and the estimation of the effect observed in these studies. Note: The study characteristics are, for example, the method of distribution into the groups, the type of blinding, the initial risk and the intervention administration schedule.

******

método de Peto

Em meta análise, um método usado para combinar razões de chances. Nota: os cálculos são diretos e de fácil interpretação, mas o resultado pode às vezes diferir substancialmente dos obtidos por outros métodos. O método de Peto é baseado no modelo de efeito fixo.

Peto method

The ratio (quotient) of the exposure odds among the cases (subjects who are ill or have died, for example) to that among the controls (subjects who are not ill or who are alive, for example).

****** 

método do custo-fricção

Um método para se estimar o custo de produção perdido, resultante da ausência de um empregado durante o período necessitado pela organização para substituir o empregado e promover o retorno ao nível inicial de produtividade. 

friction-cost method

A method of estimating the cost of the production loss resulting from the absence of an employee during the period needed by the organization to replace the employee and return to the initial level of productivity.

******

método do perfil de confiança

meta-análise baseada em estatística Bayesiana, para combinar resultados de múltiplos estudos que tem diferentes projetos de pesquisa, tais como ensaios randomizados controlados e estudos observacionais, pelo ajuste dos resultados de cada estudo individual em função de seus viéses metodológicos antes de se combinar os resultados numa distribuição de probabilidade para o(s) parâmetro(s) de interesse.

confidence profile method

A meta-analysis based on Bayesian statistics for combining results of multiple studies that have different research designs, such as randomized controlled trials and observational studies, by adjusting the results of each individual study for its methodological biases before combining the results into a probability distribution for the parameter(s) of interest.

******

mini-HTA

Relatório que inclui uma revisão compreensiva e sistemática de literatura, ou uma revisão sistemática de evidências de alto nível, avaliando a segurança e a efetividade de uma tecnologia, porém sem incluir uma análise de custo-efetividade da tecnologia. Nota 1: o relatório sempre: descreve as características do uso atual da tecnologia;  criticamente avalia a qualidade da base de evidência;  provê informação sobre custos e impacto financeiro. Nota 2: o relatório pode opcionalmente discutir considerações organizacionais. Nota 3: um "mini-HTA" pode ser tão rigoroso quanto um relatório HTA, mas tipicamente tem um escopo restrito para ser produzido rapidamente. Nota 4: termos relacionados incluem Avaliação de tecnologia em saúde, relatório HTA, revisão rápida, nível de evidência.

mini-HTA

A report that includes a comprehensive systematic literature review, or a systematic review of high level evidence, evaluating the safety and effectiveness of a technology, but that does not include an analysis of the cost-effectiveness of the technology. Note 1: The report always: 
• describes the characteristics and current use of the technology; 
• critically appraises the quality of the evidence base; and 
• provides information on costs and financial impact. Note 2: The report may optionally discuss organisational considerations Note 3: A “mini-HTA” may be as rigorous as an HTA report but typically has a restricted scope and so is quicker to produce. Note 4: Related terms include health technology assessment, HTA report, rapid review, level of evidence.

******

minimização

Um método de alocação da intervenção para obter grupos de estudo que sejam semelhantes para várias variáveis. Nota: este método pode ser usado sem um componente de randomização. 

minimization

A method of intervention allocation for obtaining study groups that are very similar for several variables. Note: This method can be used with or without a randomization component. Alternate spelling: minimisation.

******

mistura de casos

todas as características de um estudo populacional que podem influenciar o efeito ou a escolha do tratamento e que devem ser levados em conta ao se estabelecer o desfecho do tratamento. Nota: exemplos incluem severidade de doenças  e condições coexistentes

case-mix

All the characteristics of a study population that may influence the effect or the choice of a treatment and that must be taken into account when assessing treatment outcomes. Note: Examples include disease severity and coexisting conditions.

******

modelo aditivo

um modelo no qual o efeito combinado de diversos fatores independentes é a soma dos efeitos isolados de cada fator. Nota: por exemplo, se um fator X aumenta um risco por a na ausência de Y, e um segundo fator Y aumenta o riso por b na ausência de X, o efeito combinado dos dois fatores é a+b.

additive model

A model in which the combined effect of several independent factors is the sum of the isolated effects of each factor. Note: For example, if a factor X increases a risk by a in the absence of Y, and if a second factor Y increases the risk by b in the absence of X, the combined effect of the two factors is a + b.

******

modelo de efeito fixo

Em meta-análise, um modelo estatístico que leva em conta apenas a variabilidade interna ao estudo, na avaliação do grau de incerteza (intervalo de confiança) do efeito combinado obtido em estudos. Nota: o modelo de efeito fixo assume que as unidades analisadas são unidades de interesse e, consequentemente, que compõe a população em unidades. Nesse modelo, a variação entre as estimativas do efeito de cada estudo (heterogeneidade) não afeta o intervalo de confiança. Conceitos relacionados: modelo de efeito randômico, método de Peto.

fixed-effect model

In a meta-analysis, a statistical model that takes only within-study variability into account in assessment of the degree of uncertainty (confidence interval) of the combined effect from the studies. Note: The fixed-effect model assumes that the units analysed are the units of interest and, consequently, that they make up the population of units. In such a model, variation between the estimates of effect from each study (heterogeneity) does not affect the confidence interval. (Related concepts: random effects model, Peto method)

******

modelo de efeito randômico

Numa meta análise, um modelo estatístico no qual tanto a variância interna e as variâncias entre estudos são incluidas na avaliação do grau de incerteza (intervalo de confiança) do efeito combinado dos estudos. Nota: se há uma heterogeneidade significativa entre os resultados dos estudos incluidos na meta análise, um modelo randomizado de efeito poderá proporcionar intervalos de confiança mais largo do que no modelo de efeito fixo. (Conceito relacionado: modelo de efeito fixo).

random effects model

In a meta-analysis, a statistical model in which both the within-study variance and the between-studies variances are included in the assessment of the degree of uncertainty (confidence interval) of the combined effect of the studies. Note: If there is significant heterogeneity among the results of the studies included in a meta-analysis, a random effects model will give wider confidence intervals than a fixed-effect model. (Related concepts: fixed-effect model)

******

modelo de Markov

Um tipo de modelagem quantitativa que envolve um conjunto especificado de exaustivos estados de saúde, mutuamente exclusivos, para os quais existem probabilidades transacionais de movimentação de um estado a outro, incluindo a probabilidade de permanecer no mesmo estado. Nota: tipicamente, estados possuem um período de tempo uniforme e as probabilidades transacionais permanecem constantes ao longo do tempo.

Markov model

A type of quantitative modelling that involves a specified set of mutually exclusive and exhaustive health states for which there are transitional probabilities of moving from one state to another, including the probability of remaining in the same state. Note: Typically, states have a uniform time period, and transitional probabilities remain constant over time.

******

modelo econômico

No campo da saúde, um modelo matemático dos passos clínicos que representam as escolhas-chave e as consequências das opções sendo estudadas. Nota: um modelo econômico pode ser usado para extrapolar, à partir de desfechos intermediários, os desfechos de longo prazo importantes para os pacientes.

economic model

In the health field, a mathematical model of the clinical pathway that represents the key choices and the consequences of the options studied. Note: An economic model can be used to extrapolate, from intermediate outcomes, the long-term outcomes of importance to patients.

******

modelo logístico

Um modelo de regressão estatística que estima a probabilidade de um valor de uma variável dicotômica com base em múltiplas variáveis preditoras.

logistic model

A statistical regression model that estimates the probability of a value of a dichotomous variable on the basis of multiple predictor variables.

******

modelo multiplicativo

Um modelo no qual o efeito combinado de dois ou mais fatores é o produto dos efeitos isolados de cada fator. Nota: por exemplo, se um fator X multiplica um risco por a na ausência de Y, e um segundo fator Y multiplica o risco por b na ausência de X, o efeito combinado desses dois fatores será a x b. (conceito relacionado: modelo aditivo).

multiplicative model

A model in which the combined effect of two or more factors is the product of the isolated effects of each factor. Note: For example, if a factor X multiplies a risk by a in the absence of Y, and if a second factor Y multiplies the risk by b in the absence of X, the combined effect of the two factors will be a x b. (Related concept: additive model)
