# S {-}

seguimento

Uma observação, durante um dado período, de uma pessoa, grupo ou população definida no início, de certas características daqueles ou daquilo que está sendo avaliado, para identificar as alterações no seu estado de saúde ou em certas variáveis relacionadas à saúde. Nota: se dados dos efeitos nos sujeitos da intervenção sendo estudados forem perdidos (devido aos sujeitos terem, se mudado ou saído por alguma razão),  os resultados do estudo podem ser influenciados, especialmente se alguns tipos de sujeitos forem sistematicamente perdidos do estudo pelas mesmas razões. Os investigadores devem reportar o número e tipo de sujeitos que não puderam ser avaliados, para que a possibilidade de viés possa ser considerada. Conceito relacionado: análise de intenção de tratamento.

follow-up

An observation, over a given period, of a person, group or population defined at the outset, certain characteristics of whom or of which are evaluated to identify the changes in their health status or in certain health-related variables. Note: If data on the effects on subjects of the intervention being studied are lost (because subjects have moved or have dropped out for some other reason), the study’s results may be influenced, especially if some types of subjects are systematically lost from the study for the same reasons. The investigators must report the number and type of subjects who could not be evaluated, in order that the possibility of bias may be taken into consideration. Related concept: intention-to-treat analysis

******

segurança

Um julgamento concernente à aceitação do risco (uma medida da probabilidade de um desfecho adverso e sua severidade) associado ao uso de uma tecnologia numa dada situação (por exemplo para um paciente com um particular problema de saúde) por um clínico com certo treinamento, ou na definição de um tratamento especificado.

safety

A judgment concerning the acceptability of the risk (a measure of the probability of an adverse outcome and its severity) associated with using a technology in a given situation (e.g. for a patient with a particular health problem) by a clinician with certain training, or in a specified treatment setting.

******

sensibilidade

Uma característica de performance de um teste diagnóstico, definido como a proporção de pessoas que tiveram um resultado positivo no teste e as pessoas que tiveram a doença; é calculada assim: verdadeiros positivos  ÷ (verdadeiros positivos + falsos negativos). Conceitos relacionados: acurácia, curva ROC e especificidade.

sensitivity
A characteristic of the performance of a diagnostic test, defined as the proportion of persons who have a positive test result among the persons who have the disease; it is calculated as follows: true positives ÷ (true positives + false negatives). Related concepts: accuracy, ROC curve and specificity.

******

série

Veja série de casos

series

See case series.

******

série temporal interrompida

Um estudo do efeito terapêutico de uma tecnologia através da comparação dos resultados de medições múltiplas feitas antes e depois da tecnologia ser utilizada num dado grupo de indivíduos. Nota: o valor desse tipo de estudo pode ser fortalecido pela adição de um grupo de controle no qual a tecnologia ainda não tenha sido tentada e pela observação desse grupo nos mesmos tempos. Além disso, séries temporais múltiplas podem ser estudadas pelo escalonamento na introdução da tecnologia.

interrupted time series

A study of the therapeutic effect of a technology through comparison of the results of multiple measurements taken before and after the technology is used in a given group of subjects. Note: The value of this type of study can be strengthened by the addition of a control group in which the technology has not been tried and which is observed at the same points in time. Also, multiple time series can be studied by staggering the introduction of the technology. 

******

séries de casos

estudo observacional não controlado de uma intervenção ou exposição a um dado fator, e seu desfecho numa série de elementos

case series

An uncontrolled observational study of an intervention or of exposure to a given factor, and of its outcome in a series of subjects.

******

séries temporais

Uma série de medidas das mesmas variáveis realizada ao longo do tempo. Nota: uma série temporal é dita a ser interrompida quando um conjunto de medidas, feito antes de uma intervenção, é realizado ou uma alteração é feita num dado sistema, e outras medidas são feitas ao longo do tempo após a alteração.

time series

A series of measurements of the same variables taken over time. Note: A time series is said to be interrupted when a set of measurements is taken before an intervention is carried out or a change is made in a given system, and other measurements are taken over time after the change.

******

significância clínica

diferença no tamanho do efeito que os especialistas consideram significante para decisões clínicas ou estratégicas, independentemente de seu significado estatístico. Nota: num ensaio clínico com grande número de elementos, uma pequena diferença entre o grupo de intervençaõ e o grupo de controle, pode ser estatisticamente significante, mas clinicamente não importante. Num ensaio com um número pequeno de elementos, uma diferença clinicamente significativa pode ser observada, podendo não ser estatisticamente significante. Um ensaio maior pode ser necessário para confirmar  diferenças estatisticamente significantes. 

clinical significance

A difference in effect size that the experts consider significant for clinical or strategic decisions, regardless of statistical significance. Note: In a trial with a large number of subjects, a small difference between the treatment group and the control group may be statistically significant, but clinically unimportant. In a trial with a small number of subjects, an important clinical difference may be observed that is not statistically significant. A larger trial may be needed to confirm that the difference is statistically significant.

******

significância estatística

Em teste de hipóteses, uma conclusão obtida quando a hipótese nula é rejeitada, isto é, quando o valor p está abaixo do valor pré-determinado do nível alfa. (Conceito relacionado: valor p).

statistical significance 

In hypothesis testing, a conclusion drawn when the null hypothesis is rejected, i.e. when the p-value is below the pre-determined alpha level. (Related concept: p-value)

******

Simulação de Monte Carlo

A classificação de uma pessoa ou uma característica em uma categoria diferente daquela a qual deveria ter sido atribuída, levando a um viés de medição. Nota: Por exemplo, uma simulação de Monte Carlo pode ser usada para representar ou modelar muitos pacientes individuais em uma população com intervalos de valores para determinadas características de saúde ou resultados clínicos. Em alguns casos, os componentes aleatórios são adicionados aos valores de uma variável de entrada conhecida para determinar os efeitos das flutuações dessa variável nos valores da variável de saída.

Monte Carlo simulation

The classification of a person or a characteristic as being in a category other than that to which it should have been assigned, leading to a measurement bias. Note: For example, a Monte Carlo simulation can be used to represent or model many individual patients in a population with ranges of values for certain health characteristics or clinical outcomes. In some cases, the random components are added to the values of a known input variable to determine the effects of fluctuations of this variable on the values of the output variable.

******

sistema precoce de alerta   

Uma unidade estável  com conexões e fontes confiáveis, com o objetivo de: identificar novas tecnologias  que tenham potencial para provocar grande impacto nos serviços de saúde; filtrar e priorizar essas tecnologias para selecionar aquelas que provavelmente  terão impacto na saúde, serviços e orçamentos; e estabelecer esse impacto.


early warning system

A stable unit with reliable connections and sources which aims to: identify new technologies that have the potential to make a large impact on health services; filter and prioritize these technologies to select those most likely to have a impact on health, services and budgets; and assess that impact.

******

sistema precoce de alerta e sistema de alerta

Um sistema que pretende identificar, filtrar e priorizar tecnologias em saúde, novas e  emergentes, ou novos usos de intervenções existentes; para estabelecer ou predizer seu impacto na saúde, serviços de saúde e/ou na sociedade; e para disseminar informação. Nota 1: "filtrar" é um processo para remover, da lista de tecnologias originadas do processo de identificação,  as tecnologias que não são relevantes para o sistema precoce de alerta e para o sistema de alerta. Nota 2: "priorizar" é um processo para determinar a significância das tecnologias filtradas ou a ordem com que devem ser analisadas, de acordo com a sua importância relativa para os objetivos do sistema precoce de alerta e do sistema de alerta. Nota 3: sinônimos incluem sistema precoce de aviso; sistema de prospecção do horizonte; sistema EAA.

early awareness and alert system  

A system that aims to identify, filter and prioritize new and emerging health technologies, or new uses of existing interventions; to assess or predict their impact on health, health services and/or society; and to disseminate information. Note 1: ‘Filter’ is a process to remove technologies that are not relevant to the early awareness and alert system from the list of technologies originating from the identification process. Note 2: ‘Prioritize’ is a process to determine the significance of, or order for dealing with, filtered technologies according to their relative importance to the aims of the early awareness and alert system. Note 3: Synonyms include early warning system; horizon scanning system; EAA system
