# T {-}

tabela de contingência

Tabela apresentando uma classificação cruzada de dados categóricos, de modo que essas categorias de uma característica seja, indicadas horizontalmente (em linhas) e as categorias da outra característica sejam indicadas verticalmente (em colunas). Nota: cada célula da tabela indicará o número ou proporção de indivíduos que tenham ambas as características mencionadas na linha e na coluna. A tabela de contingência mais simples é a quádrupla, ou tabela 2x2, que é usada em ensaios clínicos, por exemplo, para comparar desfechos dicotômicos em dois grupos.

contingency table

A table presenting a cross-classification of categorical data such that the categories of one characteristic are indicated horizontally (in rows) and the categories of another characteristic are indicated vertically (in columns).  Note: Each cell of the table will indicate the number or proportion of individuals who have both the characteristic on its row and in its column. The simplest contingency table is the fourfold, or 2x2 table, which is used in clinical trials, for example, to compare dichotomous outcomes for two groups.

******

tabela de evidências

Uma tabela sumarizando características de estudos de uma particular intervenção ou problema de saúde. Nota: este tipo de tabela inclui caracteristicas tais como o plano metodológico, os sujeitos e os desfechos.

evidence table

A summary table of selected characteristics of the studies of a particular intervention or health problem. Note: This type of table includes characteristics such as the methodological plan, the subjects and the outcomes.

******

tamanho da amostra

O número de indivíduos estudados, incluindo os do grupo de intervenção e os do grupo controle, quando aplicável. Nota: em geral, um tamanho maior de amostra diminui a probabilidade de erros Tipo I (α) (falso positivo) e aumenta o poder estatístico do ensaio, isto é, diminui a probabilidade de erros Tipo II (β) (falso-negativo). Um maior tamanho de amostra diminui o efeito da variação randômica sobre a estimativa do efeito do tratamento. No projeto de um estudo, o tamanho desejado da amostra pode ser calculado usando-se uma fórmula estatística baseada nos níveis aceitáveis de erros α e β, na menor diferença entre os grupos de intervenção considerados clinicamente relevantes e na medida da variância. Conceitos relacionados: alfa e beta.

sample size

The number of subjects studied, including those in the intervention group and the control group, where applicable. Note: In general, a large sample size decreases the probability of Type I (α) (false-positive) errors and increases the statistical power of the trial, i.e. decreases the probability of Type II (β) (false-negative) errors. A large sample size decreases the effect of random variation on the estimate of a treatment effect. In designing a study, the desired sample size can be calculated using a statistical formula based on the acceptable levels of α and β errors, the smallest difference between intervention groups considered clinically relevant, and the measurement variance. Related concepts: alpha and beta.

******

tamanho do efeito

Uma medida adimensional do grau de presença de um fenômeno na população de interesse. Nota: no caso de variáveis contínuas, é geralmente definida como a diferença das médias entre os grupos experimental e o de controle, divididas pelo desvio padrão do grupo de controle ou de ambos os grupos. Quando escalas diferentes (avaliação de dor, por exemplo) são usadas para medir o desfecho, elas se tornam comparáveis. Nota: esta medida é usada para determinar o tamanho de uma amostra.

effect size

A dimensionless measure of the degree of presence of a phenomenon in the population of interest. Note: In the case of continuous variables, it is generally defined as the difference in means between the experimental and control groups, divided by the standard deviation of the control group or both groups. When different scales (pain assessment, for example) are used to measure an outcome, they become comparable. Note: This measure is used to determine the size of a sample.

******

taxa de desconto

A taxa de juros usada para determinar o valor presente de custos  e benefícos futuros. Nota: A taxa de desconto (por exemplo 3% ou 5%) é usualmente baseada em taxas de empréstimo governamentais (por exemplo, em notas de três meses do Tesouro) ou em taxas de juros de mercado onde o vencimento é equivalente ao período no qual a intervenção ou programa é avaliado.

discount rate

The interest rate used to determine the present value of future costs and benefits. Note: The discount rate (e.g. 3% or 5%) is usually based on government borrowing rates (on three-month Treasury bills, for example) or market interest rates where the maturity is equivalent to the period in which the intervention or program is evaluated.

******

taxa de evento

A proporção de membros de um grupo no qual um evento é observado duarante um peródo de tempo especificado. Nota: se um evento (por exemplo, um acidente vascular) é observado em 32 pacientes de um grupo de 100 sendo monitorados, por um ano, a taxa de acidente vascular é de 0,31 num ano.

event rate

The proportion of the members of a group in whom an event is observed over a specified period of time. Note: If an event (e.g. a stroke) is observed in 32 subjects out of a group of 100 monitored over one year, the stroke rate is 0.32 a year.

******

taxa de mortalidade

A proporção de óbitos em uma determinada população dentro de um período específico (geralmente um ano). Nota: A taxa é frequentemente expressa como um número por 100.000, para facilitar a interpretação (por exemplo, 18.3 mortes por ano por 100.000 pessoas).

mortality rate

The proportion of deaths in a given population within a specified period (usually one year). Note: The rate is often expressed as a number per 100,000, to facilitate interpretation (e.g. 18.3 deaths per year per 100,000 persons).

******

técnica de grupo nominal

Uma técnica estruturada para coletar informação de peritos (de 9 a 12 pessoas), consistindo na avaliação de questões e uma discussão. Nota: a técnica de grupo nominal é composta dos seguintes passos: 1. Antes da reunião, uma revisão da literatura é enviada aos peritos; 2. Os peritos investem alguns minutos para escrever seus comentários sobre as questões sendo estudadas; 3. Cada participante contribui com uma idéia, a qual é registrada pelo moderador num quadro; 4. Sugestões similares são então agrupadas; 5. Cada participante isoladamente atribui uma nota a cada idéia; 6. As notas individuais são tabuladas, e a tabulação é apresentada aos participantes; 7. A posição geral é discutida e é feito novo ranqueamento; 8. Os resultados são apresentados aos participantes para aprovação. (Conceito relacionado: técnica Delphi).

nominal group technique

A structured technique for gathering information from experts (9 to 12 people), consisting of an evaluation of questions and a discussion. Note: The nominal group technique is composed of the following steps: 
1. Before the meeting, a literature review is sent to the experts. 
2. The experts take a few minutes to write down their comments on the questions being studied. 
3. In turn, each participant contributes an idea, which the moderator records on a flip chart. 
4. Similar suggestions are then grouped together. 
5. Each participant privately ranks each idea. 
6. The individual ranking is tabulated, and the tabulation is presented to the participants. 
7. The overall ranking is discussed and re-ranked. 
8. The results are presented to the participants for approval. (Related concept: Delphi technique)

******

tecnologia em saúde emergente

Uma tecnologia que ainda não foi adotada pelo sistema de saúde. Nota 1: Drogas estão na fase II ou III do ensaio clínico, ou num estágio pré-lançamento; dispositivos médicos estão no estágio pré-marketing. Nota 2: termos relacionados incluem nova tecnologia em saúde.

emerging health technology

A health technology that has not yet been adopted within the healthcare system. Note 1: Pharmaceuticals are in the Phase II or III clinical trial, or pre-launch stage; medical devices are in the pre-marketing stage. Note 2: Related terms include new health technology.

******

tecnologia

A aplicação de conhecimento científico ou outro, com relação a ferramentas, técnicas, produtos, processos, métodos, modos de organização,ou sistemas - para tarefas práticas. Nota: em cuidados com a saúde, a tecnologia engloba: drogas; testes diagnósticos, incluindo indicadores e reagentes; dispositivos; equipamentos e suprimentos; procedimentos médicos e cirúrgicos; sistemas de suporte; sistemas organizacionais e de gestão utilizados na prevenção, rastreamento, diagnóstico, tratamento e reabilitação. (conceito relacionado: tecnologia em saúde).

technology

The application of scientific or other organized knowledge – relating to tools, techniques, products, processes, methods, modes of organisation, or systems – to practical tasks. Note: In health care, technology encompasses: drugs; diagnostic tests, including indicators and reagents; devices; equipment and supplies; medical and surgical procedures; support systems; and organizational and managerial systems used in prevention, screening, diagnosis, treatment and rehabilitation. (Related concept:health technology).

******

tecnologia em saúde

tecnologia em saúde é definida como uma intervenção que pode ser usada para promover a saúde, prevenir, diagnosticar ou tratar males agudos ou crônicos, ou para a reabilitação. Tecnologias em saúde incluem drogas, dispositivos, procedimentos e sistemas de saúde utilizados nos cuidados da saúde.

health technology

 health technology is defined as an intervention that may be used to promote health, to prevent, diagnose or treat acute or chronic disease, or for rehabilitation.  Health technologies include pharmaceuticals, devices, procedures and organizational systems used in health care.

******

tecnologia em saúde - obsoleta 

Uma tecnologia em saúde que não seja mais o padrão de cuidados ou cujo benefício clínico, segurança ou eficiência em custo tenha sido superada por tecnologias alternativas disponíveis. Nota 1: termos relacionados incluem desinvestimento

obsolete health technology

A health technology that is no longer the standard of care or whose clinical benefit, safety or cost-effectiveness has been superseded by available alternative technologies. Note 1: Related terms include disinvestment

******

teoria fundamentada

Uma teoria resultante da coleta sistemática e da análise de informação sobre o processo de pesquisa com o objetivo de construir uma teoria de base empírica em relação a fenômenos sociais nos quais pouca análise tenha sido feita.

grounded theory

A theory resulting from the systematic gathering and analysis of information through the research process, with the objective of building empirically based theories in relation to social phenomena regarding which little analysis has been done.

******

teste de hipóteses

Um método de inferência estatística para avaliação da plausibilidade da hipótese nula à luz dos dados observados. Nota: a hipótese nula é assumida como verdadeira no início, mas, se a mesma provar estar errada quando os dados observados forem observados, ela será rejeitada em favor da hipótese alternativa (negativa para a hipótese nula).

hypothesis testing

A method of statistical inference for evaluating the plausibility of the null hypothesis in the light of the observed data. Note: The null hypothesis is assumed to be true at the outset, but, if that assumption proves wrong when the observed data are examined, it is rejected in favour of the alternative hypothesis (negative of the null hypothesis).

******

teste de Mante-Haentzel

Um teste qui-quadrado para levar em conta variávei categóricas confundidoras, ao se fazer a soma ponderada das associações em cada uma das categorias, denominadas estratos (strata). Nota: em meta-análise, os estratos consistem nos vários estudos incluidos.

Mante-Haentzel test

A chi-square test for taking categorical confounding variables into account when doing a weighted sum of the associations in each of the categories, called strata. Note: In meta-analyses, the strata are the various studies included.

******

teste estatístico

Veja teste de hipóteses.

statistical test

See hypothesis testing.

******

teste múltiplo

Diversos testes estatísticos realizados sobre as mesmas observações. Nota: num estudo, o tamanho da amostra e o nível alfa são estabelecidos de acordo com o princípio de que uma hipótese nula única será testada ao final do estudo, uma vez que os dados tenham sido colhidos. Se mais do que um teste estatístico for realizado, isto é, se forem feitas comparações de várias intervenções, ou testes em variáveis distintas, em momentos distintos ou em sub-grupos diferentes, haverá um aumentoda probabilidade de ocorrência do erro de Tipo 1 (alfa) planejado. Alguns métodos estatísticos se propõe a considerar testes múltiplos, mas são controversos.

multiple testing

Several statistical tests done on the same observations. Note: In a study, the sample size and the alpha level are set according to the principle that a single null hypothesis will be tested at the end of the study, once all the data have been gathered. If more than one statistical test is undertaken, e.g. pairwise comparisons of several interventions, or tests on different variables, at different timepoints or on different sub-groups, there will be an increase in the planned overall Type I error (alpha) probability. Some statistical methods are proposed to take multiple testing into account, but they are controversial.

******

tomada de decisão baseada em evidências

A consideração dos achados de pesquisas médicas e científicas, no processo de tomada de decisão. Sinônimo: tomada de decisão por evidência informada.

evidence-based decision making

The consideration of the findings from scientific and medical research in the decision-making process. Syn.: evidence-informed decision making

******

triagem

Um serviço de saúde pública no qual os membros de uma população de risco de uma doença ou de sua complicação é submetido a perguntas ou oferecido um teste, para identificar quais indivíduos estão num risco suficientemente alto que justifique testes diagnósticos ou tratamentos adicionais.

screening

A public health service in which members of a population at risk for a disease or its complications are asked questions or offered a test, to identify those individuals who are at sufficiently high risk that further diagnostic tests or treatments are justified.
