# V {-}

validade

A habilidade do resultado de uma medida ou estudo ser  e livre de viéses (erros sitemáticos).

validity

The ability of the result of a measurement or study to be accurate and free of bias (systematic errors). Note: In the context of a study, two types of validity are recognized: internal validity and external validity. In the context of measurement, there are several types of validity: construct validity, content validity, face validity, etc. Related concept: methodological quality

******

validade do estudo

A capacidade de um estudo em permitir conclusões corretas quando forem levados em conta: os métodos de pesquisa, a representatividade da validade interna da amostra do estudo e a natureza da população da qual foi feito o recrutamento com validade externa.

study validity

The ability of a study to allow for the drawing of correct conclusions when the research methods, the representativeness of the study sample internal validity and the nature of the population from which it is recruited external validity are taken into account.

******

validade externa

A habilidade de um projeto de pesquisa prover descobertas que possam ser generalizadas para outras populações, contextos e períodos. Sinônimo: generalizabilidade. Conceito relacionado: aplicabilidade.

external validity

The ability of a research design to provide findings that can be generalised to other populations, contexts and periods. Syn.: generalizability. Related concept: applicability

******

validade interna

A habilidade de um projeto de pesquisa de representar a relação verdadeiramente causal entre uma intervenção e um efeito em circunstâncias particulares da pesquisa. Nota: se a organização interna de um estudo conduz a uma distorção na medida da estimativa, tal medida perde sua validade interna. Isso é o que ocorre quando, por exemplo, uma pessoa é pesada com uma escala defeituosa. Com uma escala bem calibrada um estudo etiológico deve estar livre de defeitos internos devidos à distorção nas medidas. Esses defeitos podem ser encontrados em três estágios do estudo: na seleção do indivíduo, na coleta de informações e no estágio de análise.

internal validity

The ability of a research design to represent the true causal relationship between an intervention and an effect in the particular circumstances of the research.Note: If the internal organization of a study leads to distortion in the estimation measurement, that measurement lacks internal validity. This is what happens when, for example, a person is weighed using a defective scale. As with a well-calibrated scale, an etiological study must be free of measurement-distorting internal defects. These defects may be encountered at three stages in the study: the subject selection, information-gathering and analysis stages. 

******

valor

Uma medida cardinal da preferência por um estado de saúde específico ou por um desfecho de saude, medido sob certa incerteza. Nota: esta variável também é usada para dar uma descrição geral e balanceada dos (custos) aspectos  positivos e negativos de uma situação (por exemplo: o melhor valor para o investimento). (conceitos relacionados: utilidade e preferencia). Nota: de acordo com Drummond, valor é uma preferência livre de riscos (situação de certeza) e utilidade é a preferência medida sob incerteza.

value

A cardinal measure of the preference for a specific health status or health outcome, measured under uncertainty. Note: This variable is also used to give an overall and balanced description of the positive and negative (costs) aspects of a situation (e.g. best value for money). (Related concepts: utility and preference.) Note: According to Drummond, value is risk-free preference (situation of certainty) and utility is preference measured under uncertainty.

******

valor atípico

Um valor observado que por ser tão diferente dos demais valores observados leva a uma suspeita de que foi cometido um erro ou que ocorreu um acaso.

outlier

An observed value that is so different from the other observation values as to lead one to suspect that an error has been made or that chance has played a part.

******

valor p

Em teste de hipóteses, a probabilidade que um parâmetro a ser testado tenha um valor tão ou mais extremo que o valor que seria observado se a hipótese nula fosse verdadeira. Nota: se o valor de p associado com o teste estatístico for maior ou igual do que o nível alfa que foi determinado (0,01 ou 0,05, por exemplo), isso significa que a associação ou a diferença observada pode ser devida ao acaso e ue a hipótese nula não pode ser rejeitada. No entanto, se o valor for menor do que o nível alfa que foi determinado, a associação ou diferença é estatísticamente significativa e a hipótese nula  é rejeitada.

p value

In hypothesis testing, the probability that a parameter to be tested has a value as extreme or more extreme than the value that would be observed if the null hypothesis were true. Note: If the p value associated with the statistical test is equal to or greater than the alpha level that was determined (0.01 or 0.05, for example), this means that the association or difference observed may be due to chance and that the null hypothesis cannot be rejected. However, if the p value is less than the alpha level that was determined, the association or difference is statistically significant and the null hypothesis is rejected. Alternate spelling: p-value

******

valor preditivo negativo (VPN)

Uma característica de desempenho de teste, definida como a proporção de pessoas que não tem a doença entre aquelas que tem um resultado negativo do teste diagnóstico; é calculada da seguinte forma: verdadeiros negativos  ÷ (verdadeiros negativos + falsos negativos). Nota: o VPN varia com a prevalência da doença na população de interesse. Conceito relacionado: valor preditivo positivo.

negative predictive value (NPV)

A test performance characteristic, defined as the proportion of persons who do not have the disease among those who have a negative diagnostic test result; it is calculated as follows: true negatives ÷ (true negatives + false negatives). Note: The NPV varies with the prevalence of the disease in the population of interest. Related concept: positive predictive value.

******

valor preditivo positivo (VPP)

Uma característica de um teste de performance, definida como a proporção de pessoas com um resultado positivo num teste diagnóstico  que possui a doença; é calculada da seguinte forma: verdadeiros positivos  ÷ (verdadeiros positivos + falsos positivos). Nota: o VPP varia com a prevalência da doença na população de interesse. Conceito relacionado: valor preditivo negativo).

positive predictive value (PPV)

A test performance characteristic, defined as the proportion of persons with a positive result in a diagnostic test who have the disease; it is calculated as follows: true positives ÷ (true positives + false positives). Note: The PPV varies with the prevalence of the disease in the population of interest. Related concept: negative predictive value.

******

valoração da contingência

Método para determinação do valor monetário de uma opção ou de um desfecho clínico, por meio de pesquisas nas quais as pessoas sejam expostas a situações e questionadas sobre o preço máximo que aceitariam pagat por essa opção ou por esse desfecho clínico

contingent valuation

A method for determining the monetary value of an option or clinical outcome by means of surveys in which people are presented with situations and asked what the maximum price is that they would be willing to pay for this option or clinical outcome.

******

variância

Uma medida da variação apresentada por um conjunto de observações, definida pela soma dos quadrados dos desvios da média, dividida pelo número de graus de liberdade no conjunto de observações.

variance

A measure of the variation shown by a set of observations, defined by the sum of the squares of deviations from the mean, divided by the number of degrees of freedom in the set of observations.

******

variável

Um fato que pode ter diferentes valores. Nota: os valores medidos num estudo são dados.

variable

A factor that can have different values. Note: The values measured in a study are data.

******

viés

em geral, qualquer fator que distorce a natureza verdadeira de um evento ou observação. Em investigações clínicas, um viés é qualquer fator sistemático distinto daquele da intervenção de interesse que afeta a magnitude (i.e. tende a aumentar ou diminuir) uma diferença observada no desfecho de grupo em tratamento ou de um grupo de controle. O viés diminui a acurácia (embora não necessáriamente a precisão) de uma observação. Randomização é uma técnica usada para reduzir esse tipo de viés. O viés também se refere a um ponto de vista prejudicado ou parcial que poderia afetar a interpretação de um problema. Cegagem dupla é uma técnica usada para reduzir esse tipo de viés.

bias

In general, any factor that distorts the true nature of an event or observation. In clinical investigations, a bias is any systematic factor other than the intervention of interest that affects the magnitude of (i.e. tends to increase or decrease) an observed difference in the outcomes of a treatment group and a control group. Bias diminishes the accuracy (though not necessarily the precision) of an observation. Randomization is a technique used to decrease this form of bias. Bias also refers to a prejudiced or partial viewpoint that would affect someone's interpretation of a problem. Double blinding is a technique used to decrease this type of bias.

******

viés de atrito

um viés associado com a saída ou com a exclusão diferencial de objetos de um estudo. Nota: se os objetos sairem por alguma razão, sua exclusão da análise poderá causar uma estimativa exagerada da efetividade da intervenção. A saída diferencial dos objetos pode ser devida a um viés de seleção num estudo experimental comparativo ou num estudo observacional de coorte.

attrition bias

A bias associated with the dropping out or the differential exclusion of subjects from a study. Note: If subjects drop out of the study for some reason, their exclusion from the analysis could lead to an overestimate of the effectiveness of the intervention. The differential dropping out of subjects may be due to a selection bias in a comparative experimental study or cohort observation study.

******

viés de contexto

Um viés de medida devido à influência do contexto em estudo, ou na interpretação dos resultados do estudo. Nota: por exemplo, quando testes são feitos em grupos com alta prevalência de uma doença, os leitores tendem a interpretar os resultados como anomalias. Um fator de contexto também pode ser um fator de prognóstico em alguns casos,e, quando isso ocorre, pode levar a um viés de confusão. Além disso, a avaliação da efetividade de programas de suporte para aderência de tratamento antiretroviral pode levar a resultados questionáveis se o determinantes sociais da saúde, tais como o acesso a água potável no sub-Saara africano ou a pobreza de pessoas de rua no Canadá não foram levadas em consideração.

context bias

A measurement bias due to the influence of the study’s context on the interpretation of the study’s results. Note: For example, when tests are done in groups with a high prevalence of a disease, readers are more likely to interpret the results as anomalies. A contextual factor may also be a prognostic factor in some cases, and, if that happens, it may lead to a confusion bias. Also, evaluation of the effectiveness of support programs for antiretroviral treatment compliance may lead to questionable results if social determinants of health, such as access to drinking water in sub-Saharan Africa or the poverty of homeless persons in Canada have not been taken into account.

******

viés de cruzamento

Viés de confusão que ocorre quando os elementos incluidos no grupo experimental não recebem a intervenção ou recebem outra intervenção, ou quando alguns elementos do grupo de controle recebem a intervenção. Nota: se os resultados desses elementos forem analisados com aqueles do seu grupo original, esse tipo de viés tenderá a "diluir" (diminuir) o efeito observado do tratamento.

crossover bias

A confusion bias that occurs when the subjects assigned to the experimental group do not receive the intervention or receive another intervention, or when some subjects in the control group receive the intervention. Note: If these subjects’ results are analysed with those of their original group, this type of bias will tend to “dilute” (diminish) the observed treatment effect.

******

viés de defasamento temporal

Um tipo de viés devido a limites temporais de um método de pesquisa de literatura com possibilidade de afetar a inclusão de estudos numa revisão sistemática ou em qualquer outro tipo de síntese de literatura. Nota: tal viés pode ocorrer quando a direção (positiva ou negativa) ou o poder (significância estatística) de um estudo  resulta no atraso de sua publicação. 

time lag bias

A form of bias due to the temporal limits of a literature search method likely to affect the inclusion of studies in a systematic review or any other form of literature synthesis. Note: Such bias may occur when the direction (positive or negative) or the strength (statistical significance) of a study’s results delays its publication. Alternate spelling: time-lag bias

******

Viés de detecção

Um viés de medida devido a diferenças sistemáticas entre os grupos sendo comparados e o modo como os desfechos foram apurados.

detection bias

A measurement bias due to systematic differences between the compared groups in how the outcomes are ascertained.

******

viés de execução

Um viés de confusão devido à diferenças sistemáticas nos cuidados recebidos fora da intervenção sendo avaliada. Nota: por exemplo, se os indivíduos sabem a que grupo pertencem, eles tendem a usar outras formas de cuidados. Se os que proporcionam os cuidados tiverem a mesma informação, eles podem trtar indivíduos diferentemente, de acordo com o grupo ao qual pertençam. O cegamento (tanto para os recebedores quanto para os provedores de cuidados) é utiliziado, entre outras medidas, como proteção contra o viés de execução.

performance bias

A confusion bias due to systematic differences in care received outside the intervention being evaluated. Note: For example, if subjects know which group they are in, they are more likely to use other forms of care. If care providers have the same information, they may treat the subjects differently, according to what group they are in. Blinding (both the recipients and the providers of care) is used to, among other things, protect against performance bias.

******

viés de lingua

Um tipo de viés relacionado a uma pesquisa restrita de literatura que exclui certos estudos, em função da língua em que foi publicada, numa revisão sistemática ou qualquer outra forma de síntese literária.

language bias

A form of bias linked to a restrictive literature search that excludes certain studies, because of the language in which they are published, from a systematic review or any other form of literature synthesis.

******

viés de medida

Um viés introduzido pela medida incorreta da exposição de um desfecho aos participantes de um estudo. Nota 1: o viés de medida pode ser introduzido pelo observador, pelos participantes do estudo ou pelas ferramentas de medida. Nota 2: sinônimos: incluem viés de informação e viés de observação.

measurement bias

A bias introduced by incorrect measurement of the exposure or outcome status of participants in a study. Note 1: Measurement bias can be introduced by the observer, the study participants or the measurement tools. Note 2: Synonyms include information bias and observation bias.

******

viés de publicação

Um viés devido a estudos sendo publicados, baseados na natureza e direção dos seus resultados. Exemplo: um estudo com resultados estatisticamente significantes favorecendo a intervenção de interesse pode ter maior possibilidade de ser publicado.

publication bias

A bias due to studies being published based on the nature and direction of their results. Example: A study with statistically significant results favouring the intervention of interest may have a greater likelihood of being published.

******

viés de seleção

Um tipo de viés devido a um erro na estimativa do efeito de uma intervenção pelo modo como os indivíduos foram selecionados na população de interesse. Nota: existe viés de selecão em estudos de coorte se o recrutamento dos indivíduos expostos (não expostos) for relacionado à presença da doença. Nos estudos de caso controle, o viés de seleção ocorre se o recrutamento dos casos (controle) for relacionado à exposição ao fator de interesse.

selection bias

A type of bias due to an error in the estimation of the effect of an intervention because of the way in which the subjects were selected in the population of interest. Note: There is selection bias in cohort studies if the recruitment of the subjects who are exposed (not exposed) is linked to the presence of the disease. In case-control studies, selection bias occurs if the recruitment of the cases (controls) is linked to exposure to the factor of interest.

******
viés de seleção de paciente

veja viés de seleção

patient selection bias

See selection bias.

******

viés de trabalho

Veja víés de verificação.

workup bias

See verification bias.

******

viés de verificação

É um tipo de viés de medição em que os resultados de uma prova de diagnóstico afetam se o procedimento padrão-ouro é usado para verificar o resultado do teste. Este tipo de viés também é conhecido como "viés de referência" ou "viés de trabalho"

verification bias

See: workup bias.

******

viés do entrevistador

Um viés que resulta da ação de um entrevistador ao extrair, registrar ou interpretar informações de uma entrevista.

interviewer bias

A bias that results from the action of an interviewer when eliciting, recording or interpreting information from an interview. 

******

vocabulário controlado

Um sistema de termos que possuem, entre outras características, definições, uma estrutura hierarquica e referências cruzadas, usadas para indexar e pesquisar o conjunto de dados numa base de dados bibliográfica, fatual ou em qualquer outra. Nota: por exemplo, o vocabulário controlado MeSH usado no MEDLINE e em outras bases de dados MEDLARS da United States National Library of Medicine

controlled vocabulary

A system of terms with, among other things, definitions, a hierarchical structure and cross-references, used to index and search a body of data in a bibliographic, factual or other database. Note: For example, the MeSH controlled vocabulary used in MEDLINE and the other MEDLARS databases of the United States National Library of Medicine.
