# B {-}
banco de dados bibliográfico

fonte computadorizada e indexada de citações descrevendo documentos tais como artigos de jornais e relatórios científicos. Nota: as citações tipicamente incluem o(s) nome(s) do autor(es), o titulo, a fonte, um resumo e, quando aplicavel, informações relacionadas (incluindo o texto completo em alguns casos). Exemplos: MEDLINE e EMBASE.

bibliographic database

An indexed computerized or printed source of citations, describing documents such as journal articles and scientific reports. Note: The citations typically include the name(s) of the author(s), the title, the source, an abstract and, where applicable, related information (including the full text in some cases). Example: MEDLINE and EMBASE. 

******

base de dados de ATS

Uma base de dados contendo relatórios sobre avaliações de tecnologia na saúde em desenvolvimento e completadas. Nota: essa base de dados é gerenciada pelo CRD (Centre for Reviews and Dissemination - centro de revisões e disseminação) em colaboração com o secretariado da INAHTA. Está disponível na Livraria Cochrane no site do CRD (http://www.york.ac.uk/inst/crd/).

HTA database

A database containing the reports on ongoing and completed health technology assessments. Note: This database is managed by the Centre for Reviews and Dissemination (CRD) in collaboration with the INAHTA Secretariat. It is available in the Cochrane Library and on the CRD site (http://www.york.ac.uk/inst/crd/).

******

base de dados factual

Uma fonte indexada e computadorizada ou impressa que provê acesso direto a informações tais como guias para diagnóstico e tratamento, estatísticas e diretórios de instituições. Outra definição: uma coleção extensa e considerada completa, de fatos e dados sobre materiais num campo especializado, disponíveis para análise e aplicação. Nota: a coleção pode ser computadorizada através de vários métodos modernos de pesquisa bibliográfica. Este conceito difere do banco de dados bibliográfico, que se limita a coleções de citações.

factual database

An indexed computerized or printed source that provides direct access to information such as guidelines for diagnosis and treatment, statistics, and directories of institutions. Other definition: An extensive collection, deemed complete, of facts and data from materials in a specialized field, made available for analysis and application. Note: The collection may be computerized through various modern literature search methods. This concept differs from that of a bibliographic database, which is limited to collections of citations.

******

base do estudo

Uma população estudada numa particular localização por um período de tempo especificado.

study base

A population studied in a particular location over a specified period of time.

******

benefício líquido

O benefício de uma opção em unidades monetárias, menos o  seu custo total em unidades monetárias. Nota: o benefício líquido é um critério básico de decisão na análise de custo-benefício (ACB).

net benefit

The benefit of an option in monetary units, minus its total cost in monetary units. Note: Net benefit is a basic decision criterion in cost-benefit analysis (CBA).

******

benefício marginal

O benefício adicional produzido pelo uso de recursos adicionais, expressos, por exemplo, em unidades de desfecho em saúde.

marginal benefit

The additional benefit produced by the use of additional resources, expressed, for example, in units of health outcome.

******

beta

em teste de hipóteses, a probabilidade de erro do Tipo II, i.e. a probabilidade de se concluir incorretamente que a hipótese nula é verdadeira. Nota: por exemplo, beta poderia ser a probabilidade de se concluir que uma intervenção não é efetiva quando ela tem um efeito verdadeiro. (1-beta) é o poder estatístico de um teste permitindo a rejeição de uma hipótese nula que seja verdadeiramente falsa (i.e. detectando o efeito de uma intervenção que relamente existe)

beta

In hypothesis testing, the probability of a Type II error, i.e. the probability of concluding incorrectly that a null hypothesis is true. Note: For example, β could be the probability of concluding that an intervention is not effective when it has a true effect. (1-β) is the statistical power of a test allowing for rejection of a null hypothesis that is truly false (e.g. detecting the effect of an intervention that truly exists).

******

Biblioteca Cochrane

conjunto de bases de dados atualizadas trimestralmente, projetadas para prover informação científica e evidências para suportar a tomada de decisões no campo da saúde, publicadas em CD-ROM e na Internet. Nota: as bases de dados da Biblioteca Cochrane são: o banco de dados Cochrane de revisões sistemáticas; a central  de registro de ensaios controlados da Cochrane; o banco de dados de resumos de revisões de efeitos da Cochrane; o banco de dados de Avaliação de Tecnologias em Saúde e o banco de dados NHS de avaliação econômica.

Cochrane library

A collection of databases updated quarterly, designed to provide scientific information and evidence to support decision making in the health field, published on CD-ROM and on the Internet. Note: The Cochrane Library databases are: the Cochrane Database of Systematic Reviews, the Cochrane Central Register of Controlled Trials, the Database of Abstracts of Reviews of Effects, the Cochrane Methodology Register, the Health Technology Assessment database and the NHS Economic Evaluation database.

******

Bioética

campo de investigação compreendendo a análise de questões éticas e dilemas morais pertencentes ao estudo, classificação e manipulação de vida biológica, especialmente na saúde humana.

bioethics

A field of inquiry comprising the analysis of ethical issues and moral dilemmas pertaining to the study, classification, and manipulation of biological life, especially human health.

